//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.01 at 10:52:58 AM EST 
//


package edu.pitt.gallowdd.persephone.parameters;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for agentJavaClassXmlEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="agentJavaClassXmlEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="edu.pitt.gallowdd.persephone.agent.Person"/&gt;
 *     &lt;enumeration value="edu.pitt.gallowdd.persephone.agent.TEST"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "agentJavaClassXmlEnum")
@XmlEnum
public enum AgentJavaClassXmlEnum {

    @XmlEnumValue("edu.pitt.gallowdd.persephone.agent.Person")
    EDU_PITT_GALLOWDD_PERSEPHONE_AGENT_PERSON("edu.pitt.gallowdd.persephone.agent.Person"),
    @XmlEnumValue("edu.pitt.gallowdd.persephone.agent.TEST")
    EDU_PITT_GALLOWDD_PERSEPHONE_AGENT_TEST("edu.pitt.gallowdd.persephone.agent.TEST");
    private final String value;

    AgentJavaClassXmlEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AgentJavaClassXmlEnum fromValue(String v) {
        for (AgentJavaClassXmlEnum c: AgentJavaClassXmlEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
