//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.01 at 10:52:58 AM EST 
//


package edu.pitt.gallowdd.persephone.parameters;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for agentAsignmentTypeXmlEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="agentAsignmentTypeXmlEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="HOME"/&gt;
 *     &lt;enumeration value="BANKER"/&gt;
 *     &lt;enumeration value="BANKER_PT"/&gt;
 *     &lt;enumeration value="SHIFT_24HR"/&gt;
 *     &lt;enumeration value="SHIFT_16HR_1ST_TURN_2ND_TURN"/&gt;
 *     &lt;enumeration value="SHIFT_16HR_2ND_TURN_3RD_TURN"/&gt;
 *     &lt;enumeration value="STEADY_1ST_TURN"/&gt;
 *     &lt;enumeration value="STEADY_1ST_TURN_PT"/&gt;
 *     &lt;enumeration value="STEADY_2ND_TURN"/&gt;
 *     &lt;enumeration value="STEADY_2ND_TURN_PT"/&gt;
 *     &lt;enumeration value="STEADY_3RD_TURN"/&gt;
 *     &lt;enumeration value="STEADY_3RD_TURN_PT"/&gt;
 *     &lt;enumeration value="WEEKEND_SHIFT_24HR"/&gt;
 *     &lt;enumeration value="WEEKEND_SHIFT_16HR_1ST_TURN_2ND_TURN"/&gt;
 *     &lt;enumeration value="WEEKEND_SHIFT_16HR_2ND_TURN_3RD_TURN"/&gt;
 *     &lt;enumeration value="PRIMARY_SCHOOL"/&gt;
 *     &lt;enumeration value="SECONDARY_SCHOOL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "agentAsignmentTypeXmlEnum")
@XmlEnum
public enum AgentAsignmentTypeXmlEnum {

    HOME("HOME"),
    BANKER("BANKER"),
    BANKER_PT("BANKER_PT"),
    @XmlEnumValue("SHIFT_24HR")
    SHIFT_24_HR("SHIFT_24HR"),
    @XmlEnumValue("SHIFT_16HR_1ST_TURN_2ND_TURN")
    SHIFT_16_HR_1_ST_TURN_2_ND_TURN("SHIFT_16HR_1ST_TURN_2ND_TURN"),
    @XmlEnumValue("SHIFT_16HR_2ND_TURN_3RD_TURN")
    SHIFT_16_HR_2_ND_TURN_3_RD_TURN("SHIFT_16HR_2ND_TURN_3RD_TURN"),
    @XmlEnumValue("STEADY_1ST_TURN")
    STEADY_1_ST_TURN("STEADY_1ST_TURN"),
    @XmlEnumValue("STEADY_1ST_TURN_PT")
    STEADY_1_ST_TURN_PT("STEADY_1ST_TURN_PT"),
    @XmlEnumValue("STEADY_2ND_TURN")
    STEADY_2_ND_TURN("STEADY_2ND_TURN"),
    @XmlEnumValue("STEADY_2ND_TURN_PT")
    STEADY_2_ND_TURN_PT("STEADY_2ND_TURN_PT"),
    @XmlEnumValue("STEADY_3RD_TURN")
    STEADY_3_RD_TURN("STEADY_3RD_TURN"),
    @XmlEnumValue("STEADY_3RD_TURN_PT")
    STEADY_3_RD_TURN_PT("STEADY_3RD_TURN_PT"),
    @XmlEnumValue("WEEKEND_SHIFT_24HR")
    WEEKEND_SHIFT_24_HR("WEEKEND_SHIFT_24HR"),
    @XmlEnumValue("WEEKEND_SHIFT_16HR_1ST_TURN_2ND_TURN")
    WEEKEND_SHIFT_16_HR_1_ST_TURN_2_ND_TURN("WEEKEND_SHIFT_16HR_1ST_TURN_2ND_TURN"),
    @XmlEnumValue("WEEKEND_SHIFT_16HR_2ND_TURN_3RD_TURN")
    WEEKEND_SHIFT_16_HR_2_ND_TURN_3_RD_TURN("WEEKEND_SHIFT_16HR_2ND_TURN_3RD_TURN"),
    PRIMARY_SCHOOL("PRIMARY_SCHOOL"),
    SECONDARY_SCHOOL("SECONDARY_SCHOOL");
    private final String value;

    AgentAsignmentTypeXmlEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AgentAsignmentTypeXmlEnum fromValue(String v) {
        for (AgentAsignmentTypeXmlEnum c: AgentAsignmentTypeXmlEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
