//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.01 at 10:52:58 AM EST 
//


package edu.pitt.gallowdd.persephone.parameters;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for distributionXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="distributionXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="normal"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="mean" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="std_dev" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="min_val" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *                   &lt;element name="max_val" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="lognormal"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="scale" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="shape" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="min_val" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *                   &lt;element name="max_val" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="uniform"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="min_val" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="max_val" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="exponential"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="mean" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="min_val" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *                   &lt;element name="max_val" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "distributionXmlType", propOrder = {
    "normal",
    "lognormal",
    "uniform",
    "exponential"
})
public class DistributionXmlType {

    protected DistributionXmlType.Normal normal;
    protected DistributionXmlType.Lognormal lognormal;
    protected DistributionXmlType.Uniform uniform;
    protected DistributionXmlType.Exponential exponential;

    /**
     * Gets the value of the normal property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionXmlType.Normal }
     *     
     */
    public DistributionXmlType.Normal getNormal() {
        return normal;
    }

    /**
     * Sets the value of the normal property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionXmlType.Normal }
     *     
     */
    public void setNormal(DistributionXmlType.Normal value) {
        this.normal = value;
    }

    /**
     * Gets the value of the lognormal property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionXmlType.Lognormal }
     *     
     */
    public DistributionXmlType.Lognormal getLognormal() {
        return lognormal;
    }

    /**
     * Sets the value of the lognormal property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionXmlType.Lognormal }
     *     
     */
    public void setLognormal(DistributionXmlType.Lognormal value) {
        this.lognormal = value;
    }

    /**
     * Gets the value of the uniform property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionXmlType.Uniform }
     *     
     */
    public DistributionXmlType.Uniform getUniform() {
        return uniform;
    }

    /**
     * Sets the value of the uniform property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionXmlType.Uniform }
     *     
     */
    public void setUniform(DistributionXmlType.Uniform value) {
        this.uniform = value;
    }

    /**
     * Gets the value of the exponential property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionXmlType.Exponential }
     *     
     */
    public DistributionXmlType.Exponential getExponential() {
        return exponential;
    }

    /**
     * Sets the value of the exponential property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionXmlType.Exponential }
     *     
     */
    public void setExponential(DistributionXmlType.Exponential value) {
        this.exponential = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="mean" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *         &lt;element name="min_val" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
     *         &lt;element name="max_val" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mean",
        "minVal",
        "maxVal"
    })
    public static class Exponential {

        protected float mean;
        @XmlElement(name = "min_val")
        protected Float minVal;
        @XmlElement(name = "max_val")
        protected Float maxVal;

        /**
         * Gets the value of the mean property.
         * 
         */
        public float getMean() {
            return mean;
        }

        /**
         * Sets the value of the mean property.
         * 
         */
        public void setMean(float value) {
            this.mean = value;
        }

        /**
         * Gets the value of the minVal property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getMinVal() {
            return minVal;
        }

        /**
         * Sets the value of the minVal property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setMinVal(Float value) {
            this.minVal = value;
        }

        /**
         * Gets the value of the maxVal property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getMaxVal() {
            return maxVal;
        }

        /**
         * Sets the value of the maxVal property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setMaxVal(Float value) {
            this.maxVal = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="scale" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *         &lt;element name="shape" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *         &lt;element name="min_val" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
     *         &lt;element name="max_val" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "scale",
        "shape",
        "minVal",
        "maxVal"
    })
    public static class Lognormal {

        protected float scale;
        protected float shape;
        @XmlElement(name = "min_val")
        protected Float minVal;
        @XmlElement(name = "max_val")
        protected Float maxVal;

        /**
         * Gets the value of the scale property.
         * 
         */
        public float getScale() {
            return scale;
        }

        /**
         * Sets the value of the scale property.
         * 
         */
        public void setScale(float value) {
            this.scale = value;
        }

        /**
         * Gets the value of the shape property.
         * 
         */
        public float getShape() {
            return shape;
        }

        /**
         * Sets the value of the shape property.
         * 
         */
        public void setShape(float value) {
            this.shape = value;
        }

        /**
         * Gets the value of the minVal property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getMinVal() {
            return minVal;
        }

        /**
         * Sets the value of the minVal property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setMinVal(Float value) {
            this.minVal = value;
        }

        /**
         * Gets the value of the maxVal property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getMaxVal() {
            return maxVal;
        }

        /**
         * Sets the value of the maxVal property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setMaxVal(Float value) {
            this.maxVal = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="mean" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *         &lt;element name="std_dev" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *         &lt;element name="min_val" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
     *         &lt;element name="max_val" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mean",
        "stdDev",
        "minVal",
        "maxVal"
    })
    public static class Normal {

        protected float mean;
        @XmlElement(name = "std_dev")
        protected float stdDev;
        @XmlElement(name = "min_val")
        protected Float minVal;
        @XmlElement(name = "max_val")
        protected Float maxVal;

        /**
         * Gets the value of the mean property.
         * 
         */
        public float getMean() {
            return mean;
        }

        /**
         * Sets the value of the mean property.
         * 
         */
        public void setMean(float value) {
            this.mean = value;
        }

        /**
         * Gets the value of the stdDev property.
         * 
         */
        public float getStdDev() {
            return stdDev;
        }

        /**
         * Sets the value of the stdDev property.
         * 
         */
        public void setStdDev(float value) {
            this.stdDev = value;
        }

        /**
         * Gets the value of the minVal property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getMinVal() {
            return minVal;
        }

        /**
         * Sets the value of the minVal property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setMinVal(Float value) {
            this.minVal = value;
        }

        /**
         * Gets the value of the maxVal property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getMaxVal() {
            return maxVal;
        }

        /**
         * Sets the value of the maxVal property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setMaxVal(Float value) {
            this.maxVal = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="min_val" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *         &lt;element name="max_val" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "minVal",
        "maxVal"
    })
    public static class Uniform {

        @XmlElement(name = "min_val")
        protected float minVal;
        @XmlElement(name = "max_val")
        protected float maxVal;

        /**
         * Gets the value of the minVal property.
         * 
         */
        public float getMinVal() {
            return minVal;
        }

        /**
         * Sets the value of the minVal property.
         * 
         */
        public void setMinVal(float value) {
            this.minVal = value;
        }

        /**
         * Gets the value of the maxVal property.
         * 
         */
        public float getMaxVal() {
            return maxVal;
        }

        /**
         * Sets the value of the maxVal property.
         * 
         */
        public void setMaxVal(float value) {
            this.maxVal = value;
        }

    }

}
