//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.01 at 10:52:58 AM EST 
//


package edu.pitt.gallowdd.persephone.parameters;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for modelXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="modelXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="agent" type="{http://persephone.gallowdd.pitt.edu/parameters}agentXmlType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="location" type="{http://persephone.gallowdd.pitt.edu/parameters}locationXmlType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="network" type="{http://persephone.gallowdd.pitt.edu/parameters}networkXmlType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="condition" type="{http://persephone.gallowdd.pitt.edu/parameters}conditionXmlType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "modelXmlType", propOrder = {
    "agent",
    "location",
    "network",
    "condition"
})
public class ModelXmlType {

    @XmlElement(required = true)
    protected List<AgentXmlType> agent;
    @XmlElement(required = true)
    protected List<LocationXmlType> location;
    protected List<NetworkXmlType> network;
    @XmlElement(required = true)
    protected List<ConditionXmlType> condition;

    /**
     * Gets the value of the agent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the agent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgentXmlType }
     * 
     * 
     */
    public List<AgentXmlType> getAgent() {
        if (agent == null) {
            agent = new ArrayList<AgentXmlType>();
        }
        return this.agent;
    }

    /**
     * Gets the value of the location property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the location property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationXmlType }
     * 
     * 
     */
    public List<LocationXmlType> getLocation() {
        if (location == null) {
            location = new ArrayList<LocationXmlType>();
        }
        return this.location;
    }

    /**
     * Gets the value of the network property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the network property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNetwork().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkXmlType }
     * 
     * 
     */
    public List<NetworkXmlType> getNetwork() {
        if (network == null) {
            network = new ArrayList<NetworkXmlType>();
        }
        return this.network;
    }

    /**
     * Gets the value of the condition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the condition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConditionXmlType }
     * 
     * 
     */
    public List<ConditionXmlType> getCondition() {
        if (condition == null) {
            condition = new ArrayList<ConditionXmlType>();
        }
        return this.condition;
    }

}
