//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.01 at 10:52:58 AM EST 
//


package edu.pitt.gallowdd.persephone.parameters;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.pitt.gallowdd.persephone.parameters package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.pitt.gallowdd.persephone.parameters
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DistributionXmlType }
     * 
     */
    public DistributionXmlType createDistributionXmlType() {
        return new DistributionXmlType();
    }

    /**
     * Create an instance of {@link DynamicFunctionXmlType }
     * 
     */
    public DynamicFunctionXmlType createDynamicFunctionXmlType() {
        return new DynamicFunctionXmlType();
    }

    /**
     * Create an instance of {@link ConditionXmlType }
     * 
     */
    public ConditionXmlType createConditionXmlType() {
        return new ConditionXmlType();
    }

    /**
     * Create an instance of {@link NetworkXmlType }
     * 
     */
    public NetworkXmlType createNetworkXmlType() {
        return new NetworkXmlType();
    }

    /**
     * Create an instance of {@link NetworkXmlType.NetworkAttribute }
     * 
     */
    public NetworkXmlType.NetworkAttribute createNetworkXmlTypeNetworkAttribute() {
        return new NetworkXmlType.NetworkAttribute();
    }

    /**
     * Create an instance of {@link NetworkXmlType.NetworkAttribute.Source }
     * 
     */
    public NetworkXmlType.NetworkAttribute.Source createNetworkXmlTypeNetworkAttributeSource() {
        return new NetworkXmlType.NetworkAttribute.Source();
    }

    /**
     * Create an instance of {@link LocationXmlType }
     * 
     */
    public LocationXmlType createLocationXmlType() {
        return new LocationXmlType();
    }

    /**
     * Create an instance of {@link LocationXmlType.LocationAttribute }
     * 
     */
    public LocationXmlType.LocationAttribute createLocationXmlTypeLocationAttribute() {
        return new LocationXmlType.LocationAttribute();
    }

    /**
     * Create an instance of {@link LocationXmlType.LocationAttribute.Source }
     * 
     */
    public LocationXmlType.LocationAttribute.Source createLocationXmlTypeLocationAttributeSource() {
        return new LocationXmlType.LocationAttribute.Source();
    }

    /**
     * Create an instance of {@link AgentXmlType }
     * 
     */
    public AgentXmlType createAgentXmlType() {
        return new AgentXmlType();
    }

    /**
     * Create an instance of {@link AgentXmlType.AgentAttribute }
     * 
     */
    public AgentXmlType.AgentAttribute createAgentXmlTypeAgentAttribute() {
        return new AgentXmlType.AgentAttribute();
    }

    /**
     * Create an instance of {@link AgentXmlType.AgentAttribute.Source }
     * 
     */
    public AgentXmlType.AgentAttribute.Source createAgentXmlTypeAgentAttributeSource() {
        return new AgentXmlType.AgentAttribute.Source();
    }

    /**
     * Create an instance of {@link SimulationXmlType }
     * 
     */
    public SimulationXmlType createSimulationXmlType() {
        return new SimulationXmlType();
    }

    /**
     * Create an instance of {@link PersephoneParameters }
     * 
     */
    public PersephoneParameters createPersephoneParameters() {
        return new PersephoneParameters();
    }

    /**
     * Create an instance of {@link MessageQueuingXmlType }
     * 
     */
    public MessageQueuingXmlType createMessageQueuingXmlType() {
        return new MessageQueuingXmlType();
    }

    /**
     * Create an instance of {@link ModelXmlType }
     * 
     */
    public ModelXmlType createModelXmlType() {
        return new ModelXmlType();
    }

    /**
     * Create an instance of {@link DistributionXmlType.Normal }
     * 
     */
    public DistributionXmlType.Normal createDistributionXmlTypeNormal() {
        return new DistributionXmlType.Normal();
    }

    /**
     * Create an instance of {@link DistributionXmlType.Lognormal }
     * 
     */
    public DistributionXmlType.Lognormal createDistributionXmlTypeLognormal() {
        return new DistributionXmlType.Lognormal();
    }

    /**
     * Create an instance of {@link DistributionXmlType.Uniform }
     * 
     */
    public DistributionXmlType.Uniform createDistributionXmlTypeUniform() {
        return new DistributionXmlType.Uniform();
    }

    /**
     * Create an instance of {@link DistributionXmlType.Exponential }
     * 
     */
    public DistributionXmlType.Exponential createDistributionXmlTypeExponential() {
        return new DistributionXmlType.Exponential();
    }

    /**
     * Create an instance of {@link DynamicFunctionXmlType.Parameters }
     * 
     */
    public DynamicFunctionXmlType.Parameters createDynamicFunctionXmlTypeParameters() {
        return new DynamicFunctionXmlType.Parameters();
    }

    /**
     * Create an instance of {@link ConditionXmlType.State }
     * 
     */
    public ConditionXmlType.State createConditionXmlTypeState() {
        return new ConditionXmlType.State();
    }

    /**
     * Create an instance of {@link NetworkXmlType.NetworkAttribute.Source.InitialFileLink }
     * 
     */
    public NetworkXmlType.NetworkAttribute.Source.InitialFileLink createNetworkXmlTypeNetworkAttributeSourceInitialFileLink() {
        return new NetworkXmlType.NetworkAttribute.Source.InitialFileLink();
    }

    /**
     * Create an instance of {@link NetworkXmlType.NetworkAttribute.Source.Link }
     * 
     */
    public NetworkXmlType.NetworkAttribute.Source.Link createNetworkXmlTypeNetworkAttributeSourceLink() {
        return new NetworkXmlType.NetworkAttribute.Source.Link();
    }

    /**
     * Create an instance of {@link LocationXmlType.LocationAttribute.Source.InitialFileLink }
     * 
     */
    public LocationXmlType.LocationAttribute.Source.InitialFileLink createLocationXmlTypeLocationAttributeSourceInitialFileLink() {
        return new LocationXmlType.LocationAttribute.Source.InitialFileLink();
    }

    /**
     * Create an instance of {@link LocationXmlType.LocationAttribute.Source.Link }
     * 
     */
    public LocationXmlType.LocationAttribute.Source.Link createLocationXmlTypeLocationAttributeSourceLink() {
        return new LocationXmlType.LocationAttribute.Source.Link();
    }

    /**
     * Create an instance of {@link AgentXmlType.AgentAttribute.Source.InitialFileLink }
     * 
     */
    public AgentXmlType.AgentAttribute.Source.InitialFileLink createAgentXmlTypeAgentAttributeSourceInitialFileLink() {
        return new AgentXmlType.AgentAttribute.Source.InitialFileLink();
    }

    /**
     * Create an instance of {@link AgentXmlType.AgentAttribute.Source.Link }
     * 
     */
    public AgentXmlType.AgentAttribute.Source.Link createAgentXmlTypeAgentAttributeSourceLink() {
        return new AgentXmlType.AgentAttribute.Source.Link();
    }

    /**
     * Create an instance of {@link SimulationXmlType.SyntheticEnvironment }
     * 
     */
    public SimulationXmlType.SyntheticEnvironment createSimulationXmlTypeSyntheticEnvironment() {
        return new SimulationXmlType.SyntheticEnvironment();
    }

}
