//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.01 at 10:52:58 AM EST 
//


package edu.pitt.gallowdd.persephone.parameters;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transmissionModeXmlEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="transmissionModeXmlEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="none"/&gt;
 *     &lt;enumeration value="vector"/&gt;
 *     &lt;enumeration value="proximity"/&gt;
 *     &lt;enumeration value="network"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "transmissionModeXmlEnum")
@XmlEnum
public enum TransmissionModeXmlEnum {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("vector")
    VECTOR("vector"),
    @XmlEnumValue("proximity")
    PROXIMITY("proximity"),
    @XmlEnumValue("network")
    NETWORK("network");
    private final String value;

    TransmissionModeXmlEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TransmissionModeXmlEnum fromValue(String v) {
        for (TransmissionModeXmlEnum c: TransmissionModeXmlEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
