//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:04 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.base;

import java.util.ArrayList;
import java.util.List;
import edu.pitt.gallowdd.persephone.xml.common.DatatypeXmlEnum;
import edu.pitt.gallowdd.persephone.xml.common.LocationDatatypeXmlEnum;
import edu.pitt.gallowdd.persephone.xml.common.LocationFilenameXmlEnum;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for locationXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="locationXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="data_type" type="{http://persephone.gallowdd.pitt.edu/xml/common}locationDatatypeXmlEnum"/&gt;
 *         &lt;element name="filename" type="{http://persephone.gallowdd.pitt.edu/xml/common}locationFilenameXmlEnum"/&gt;
 *         &lt;element name="latitude"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="longitude"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="elevation" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="location_attribute" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="data_type" type="{http://persephone.gallowdd.pitt.edu/xml/common}datatypeXmlEnum"/&gt;
 *                   &lt;element name="source" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="initial_file"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="convert_to_enum_function" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="link_file"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="convert_to_enum_function" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="attr_name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "locationXmlType", propOrder = {
    "dataType",
    "filename",
    "latitude",
    "longitude",
    "elevation",
    "locationAttribute"
})
public class LocationXmlType {

    @XmlElement(name = "data_type", required = true)
    @XmlSchemaType(name = "string")
    protected LocationDatatypeXmlEnum dataType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected LocationFilenameXmlEnum filename;
    @XmlElement(required = true)
    protected LocationXmlType.Latitude latitude;
    @XmlElement(required = true)
    protected LocationXmlType.Longitude longitude;
    protected LocationXmlType.Elevation elevation;
    @XmlElement(name = "location_attribute")
    protected List<LocationXmlType.LocationAttribute> locationAttribute;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String name;

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link LocationDatatypeXmlEnum }
     *     
     */
    public LocationDatatypeXmlEnum getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationDatatypeXmlEnum }
     *     
     */
    public void setDataType(LocationDatatypeXmlEnum value) {
        this.dataType = value;
    }

    /**
     * Gets the value of the filename property.
     * 
     * @return
     *     possible object is
     *     {@link LocationFilenameXmlEnum }
     *     
     */
    public LocationFilenameXmlEnum getFilename() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationFilenameXmlEnum }
     *     
     */
    public void setFilename(LocationFilenameXmlEnum value) {
        this.filename = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link LocationXmlType.Latitude }
     *     
     */
    public LocationXmlType.Latitude getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationXmlType.Latitude }
     *     
     */
    public void setLatitude(LocationXmlType.Latitude value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link LocationXmlType.Longitude }
     *     
     */
    public LocationXmlType.Longitude getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationXmlType.Longitude }
     *     
     */
    public void setLongitude(LocationXmlType.Longitude value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the elevation property.
     * 
     * @return
     *     possible object is
     *     {@link LocationXmlType.Elevation }
     *     
     */
    public LocationXmlType.Elevation getElevation() {
        return elevation;
    }

    /**
     * Sets the value of the elevation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationXmlType.Elevation }
     *     
     */
    public void setElevation(LocationXmlType.Elevation value) {
        this.elevation = value;
    }

    /**
     * Gets the value of the locationAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the locationAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocationAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationXmlType.LocationAttribute }
     * 
     * 
     */
    public List<LocationXmlType.LocationAttribute> getLocationAttribute() {
        if (locationAttribute == null) {
            locationAttribute = new ArrayList<LocationXmlType.LocationAttribute>();
        }
        return this.locationAttribute;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "csvFieldName"
    })
    public static class Elevation {

        @XmlElement(name = "csv_field_name", required = true)
        protected String csvFieldName;

        /**
         * Gets the value of the csvFieldName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCsvFieldName() {
            return csvFieldName;
        }

        /**
         * Sets the value of the csvFieldName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCsvFieldName(String value) {
            this.csvFieldName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "csvFieldName"
    })
    public static class Latitude {

        @XmlElement(name = "csv_field_name", required = true)
        protected String csvFieldName;

        /**
         * Gets the value of the csvFieldName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCsvFieldName() {
            return csvFieldName;
        }

        /**
         * Sets the value of the csvFieldName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCsvFieldName(String value) {
            this.csvFieldName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="data_type" type="{http://persephone.gallowdd.pitt.edu/xml/common}datatypeXmlEnum"/&gt;
     *         &lt;element name="source" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="initial_file"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="convert_to_enum_function" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="link_file"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="convert_to_enum_function" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="attr_name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataType",
        "source"
    })
    public static class LocationAttribute {

        @XmlElement(name = "data_type", required = true)
        @XmlSchemaType(name = "string")
        protected DatatypeXmlEnum dataType;
        protected LocationXmlType.LocationAttribute.Source source;
        @XmlAttribute(name = "attr_name", required = true)
        protected String attrName;

        /**
         * Gets the value of the dataType property.
         * 
         * @return
         *     possible object is
         *     {@link DatatypeXmlEnum }
         *     
         */
        public DatatypeXmlEnum getDataType() {
            return dataType;
        }

        /**
         * Sets the value of the dataType property.
         * 
         * @param value
         *     allowed object is
         *     {@link DatatypeXmlEnum }
         *     
         */
        public void setDataType(DatatypeXmlEnum value) {
            this.dataType = value;
        }

        /**
         * Gets the value of the source property.
         * 
         * @return
         *     possible object is
         *     {@link LocationXmlType.LocationAttribute.Source }
         *     
         */
        public LocationXmlType.LocationAttribute.Source getSource() {
            return source;
        }

        /**
         * Sets the value of the source property.
         * 
         * @param value
         *     allowed object is
         *     {@link LocationXmlType.LocationAttribute.Source }
         *     
         */
        public void setSource(LocationXmlType.LocationAttribute.Source value) {
            this.source = value;
        }

        /**
         * Gets the value of the attrName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttrName() {
            return attrName;
        }

        /**
         * Sets the value of the attrName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttrName(String value) {
            this.attrName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="initial_file"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="convert_to_enum_function" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="link_file"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="convert_to_enum_function" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "initialFile",
            "linkFile"
        })
        public static class Source {

            @XmlElement(name = "initial_file")
            protected LocationXmlType.LocationAttribute.Source.InitialFile initialFile;
            @XmlElement(name = "link_file")
            protected LocationXmlType.LocationAttribute.Source.LinkFile linkFile;

            /**
             * Gets the value of the initialFile property.
             * 
             * @return
             *     possible object is
             *     {@link LocationXmlType.LocationAttribute.Source.InitialFile }
             *     
             */
            public LocationXmlType.LocationAttribute.Source.InitialFile getInitialFile() {
                return initialFile;
            }

            /**
             * Sets the value of the initialFile property.
             * 
             * @param value
             *     allowed object is
             *     {@link LocationXmlType.LocationAttribute.Source.InitialFile }
             *     
             */
            public void setInitialFile(LocationXmlType.LocationAttribute.Source.InitialFile value) {
                this.initialFile = value;
            }

            /**
             * Gets the value of the linkFile property.
             * 
             * @return
             *     possible object is
             *     {@link LocationXmlType.LocationAttribute.Source.LinkFile }
             *     
             */
            public LocationXmlType.LocationAttribute.Source.LinkFile getLinkFile() {
                return linkFile;
            }

            /**
             * Sets the value of the linkFile property.
             * 
             * @param value
             *     allowed object is
             *     {@link LocationXmlType.LocationAttribute.Source.LinkFile }
             *     
             */
            public void setLinkFile(LocationXmlType.LocationAttribute.Source.LinkFile value) {
                this.linkFile = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="convert_to_enum_function" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "csvFieldName",
                "convertToEnumFunction"
            })
            public static class InitialFile {

                @XmlElement(name = "csv_field_name", required = true)
                protected String csvFieldName;
                @XmlElement(name = "convert_to_enum_function")
                protected String convertToEnumFunction;

                /**
                 * Gets the value of the csvFieldName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCsvFieldName() {
                    return csvFieldName;
                }

                /**
                 * Sets the value of the csvFieldName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCsvFieldName(String value) {
                    this.csvFieldName = value;
                }

                /**
                 * Gets the value of the convertToEnumFunction property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getConvertToEnumFunction() {
                    return convertToEnumFunction;
                }

                /**
                 * Sets the value of the convertToEnumFunction property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setConvertToEnumFunction(String value) {
                    this.convertToEnumFunction = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="convert_to_enum_function" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "filename",
                "csvFieldName",
                "convertToEnumFunction"
            })
            public static class LinkFile {

                @XmlElement(required = true)
                protected String filename;
                @XmlElement(name = "csv_field_name", required = true)
                protected String csvFieldName;
                @XmlElement(name = "convert_to_enum_function")
                protected String convertToEnumFunction;

                /**
                 * Gets the value of the filename property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFilename() {
                    return filename;
                }

                /**
                 * Sets the value of the filename property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFilename(String value) {
                    this.filename = value;
                }

                /**
                 * Gets the value of the csvFieldName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCsvFieldName() {
                    return csvFieldName;
                }

                /**
                 * Sets the value of the csvFieldName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCsvFieldName(String value) {
                    this.csvFieldName = value;
                }

                /**
                 * Gets the value of the convertToEnumFunction property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getConvertToEnumFunction() {
                    return convertToEnumFunction;
                }

                /**
                 * Sets the value of the convertToEnumFunction property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setConvertToEnumFunction(String value) {
                    this.convertToEnumFunction = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "csvFieldName"
    })
    public static class Longitude {

        @XmlElement(name = "csv_field_name", required = true)
        protected String csvFieldName;

        /**
         * Gets the value of the csvFieldName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCsvFieldName() {
            return csvFieldName;
        }

        /**
         * Sets the value of the csvFieldName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCsvFieldName(String value) {
            this.csvFieldName = value;
        }

    }

}
