//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:04 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.base;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.pitt.gallowdd.persephone.xml.base package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.pitt.gallowdd.persephone.xml.base
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NetworkXmlType }
     * 
     */
    public NetworkXmlType createNetworkXmlType() {
        return new NetworkXmlType();
    }

    /**
     * Create an instance of {@link NetworkXmlType.NetworkAttribute }
     * 
     */
    public NetworkXmlType.NetworkAttribute createNetworkXmlTypeNetworkAttribute() {
        return new NetworkXmlType.NetworkAttribute();
    }

    /**
     * Create an instance of {@link NetworkXmlType.NetworkAttribute.Source }
     * 
     */
    public NetworkXmlType.NetworkAttribute.Source createNetworkXmlTypeNetworkAttributeSource() {
        return new NetworkXmlType.NetworkAttribute.Source();
    }

    /**
     * Create an instance of {@link LocationXmlType }
     * 
     */
    public LocationXmlType createLocationXmlType() {
        return new LocationXmlType();
    }

    /**
     * Create an instance of {@link LocationXmlType.LocationAttribute }
     * 
     */
    public LocationXmlType.LocationAttribute createLocationXmlTypeLocationAttribute() {
        return new LocationXmlType.LocationAttribute();
    }

    /**
     * Create an instance of {@link LocationXmlType.LocationAttribute.Source }
     * 
     */
    public LocationXmlType.LocationAttribute.Source createLocationXmlTypeLocationAttributeSource() {
        return new LocationXmlType.LocationAttribute.Source();
    }

    /**
     * Create an instance of {@link AgentXmlType }
     * 
     */
    public AgentXmlType createAgentXmlType() {
        return new AgentXmlType();
    }

    /**
     * Create an instance of {@link AgentXmlType.AgentAttribute }
     * 
     */
    public AgentXmlType.AgentAttribute createAgentXmlTypeAgentAttribute() {
        return new AgentXmlType.AgentAttribute();
    }

    /**
     * Create an instance of {@link AgentXmlType.AgentAttribute.Source }
     * 
     */
    public AgentXmlType.AgentAttribute.Source createAgentXmlTypeAgentAttributeSource() {
        return new AgentXmlType.AgentAttribute.Source();
    }

    /**
     * Create an instance of {@link PersephoneBaseParameters }
     * 
     */
    public PersephoneBaseParameters createPersephoneBaseParameters() {
        return new PersephoneBaseParameters();
    }

    /**
     * Create an instance of {@link NetworkXmlType.NetworkAttribute.Source.InitialFileLink }
     * 
     */
    public NetworkXmlType.NetworkAttribute.Source.InitialFileLink createNetworkXmlTypeNetworkAttributeSourceInitialFileLink() {
        return new NetworkXmlType.NetworkAttribute.Source.InitialFileLink();
    }

    /**
     * Create an instance of {@link NetworkXmlType.NetworkAttribute.Source.Link }
     * 
     */
    public NetworkXmlType.NetworkAttribute.Source.Link createNetworkXmlTypeNetworkAttributeSourceLink() {
        return new NetworkXmlType.NetworkAttribute.Source.Link();
    }

    /**
     * Create an instance of {@link LocationXmlType.Latitude }
     * 
     */
    public LocationXmlType.Latitude createLocationXmlTypeLatitude() {
        return new LocationXmlType.Latitude();
    }

    /**
     * Create an instance of {@link LocationXmlType.Longitude }
     * 
     */
    public LocationXmlType.Longitude createLocationXmlTypeLongitude() {
        return new LocationXmlType.Longitude();
    }

    /**
     * Create an instance of {@link LocationXmlType.Elevation }
     * 
     */
    public LocationXmlType.Elevation createLocationXmlTypeElevation() {
        return new LocationXmlType.Elevation();
    }

    /**
     * Create an instance of {@link LocationXmlType.LocationAttribute.Source.InitialFile }
     * 
     */
    public LocationXmlType.LocationAttribute.Source.InitialFile createLocationXmlTypeLocationAttributeSourceInitialFile() {
        return new LocationXmlType.LocationAttribute.Source.InitialFile();
    }

    /**
     * Create an instance of {@link LocationXmlType.LocationAttribute.Source.LinkFile }
     * 
     */
    public LocationXmlType.LocationAttribute.Source.LinkFile createLocationXmlTypeLocationAttributeSourceLinkFile() {
        return new LocationXmlType.LocationAttribute.Source.LinkFile();
    }

    /**
     * Create an instance of {@link AgentXmlType.AgentAttribute.Source.InitialFile }
     * 
     */
    public AgentXmlType.AgentAttribute.Source.InitialFile createAgentXmlTypeAgentAttributeSourceInitialFile() {
        return new AgentXmlType.AgentAttribute.Source.InitialFile();
    }

    /**
     * Create an instance of {@link AgentXmlType.AgentAttribute.Source.LinkFile }
     * 
     */
    public AgentXmlType.AgentAttribute.Source.LinkFile createAgentXmlTypeAgentAttributeSourceLinkFile() {
        return new AgentXmlType.AgentAttribute.Source.LinkFile();
    }

}
