//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:27 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.synthenv;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import edu.pitt.gallowdd.persephone.xml.common.AgentDatatypeXmlEnum;
import edu.pitt.gallowdd.persephone.xml.common.AgentFilenameXmlEnum;
import edu.pitt.gallowdd.persephone.xml.common.CountryCodeXmlEnum;
import edu.pitt.gallowdd.persephone.xml.common.LocationDatatypeXmlEnum;
import edu.pitt.gallowdd.persephone.xml.common.LocationFilenameXmlEnum;
import edu.pitt.gallowdd.persephone.xml.common.PopVersionXmlEnum;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="country" type="{http://persephone.gallowdd.pitt.edu/xml/common}countryCodeXmlEnum"/&gt;
 *         &lt;element name="version" type="{http://persephone.gallowdd.pitt.edu/xml/common}popVersionXmlEnum"/&gt;
 *         &lt;element name="agent" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="agent_type" type="{http://persephone.gallowdd.pitt.edu/xml/common}agentDatatypeXmlEnum"/&gt;
 *                   &lt;element name="filename" type="{http://persephone.gallowdd.pitt.edu/xml/common}agentFilenameXmlEnum"/&gt;
 *                   &lt;element name="entry_count" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="location" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="location_type" type="{http://persephone.gallowdd.pitt.edu/xml/common}locationDatatypeXmlEnum"/&gt;
 *                   &lt;element name="filename" type="{http://persephone.gallowdd.pitt.edu/xml/common}locationFilenameXmlEnum"/&gt;
 *                   &lt;element name="entry_count" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identifier",
    "country",
    "version",
    "agent",
    "location"
})
@XmlRootElement(name = "synthetic_environment")
public class SyntheticEnvironment {

    @XmlElement(required = true)
    protected String identifier;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CountryCodeXmlEnum country;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected PopVersionXmlEnum version;
    @XmlElement(required = true)
    protected List<SyntheticEnvironment.Agent> agent;
    @XmlElement(required = true)
    protected List<SyntheticEnvironment.Location> location;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCodeXmlEnum }
     *     
     */
    public CountryCodeXmlEnum getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCodeXmlEnum }
     *     
     */
    public void setCountry(CountryCodeXmlEnum value) {
        this.country = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link PopVersionXmlEnum }
     *     
     */
    public PopVersionXmlEnum getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link PopVersionXmlEnum }
     *     
     */
    public void setVersion(PopVersionXmlEnum value) {
        this.version = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the agent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SyntheticEnvironment.Agent }
     * 
     * 
     */
    public List<SyntheticEnvironment.Agent> getAgent() {
        if (agent == null) {
            agent = new ArrayList<SyntheticEnvironment.Agent>();
        }
        return this.agent;
    }

    /**
     * Gets the value of the location property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the location property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SyntheticEnvironment.Location }
     * 
     * 
     */
    public List<SyntheticEnvironment.Location> getLocation() {
        if (location == null) {
            location = new ArrayList<SyntheticEnvironment.Location>();
        }
        return this.location;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="agent_type" type="{http://persephone.gallowdd.pitt.edu/xml/common}agentDatatypeXmlEnum"/&gt;
     *         &lt;element name="filename" type="{http://persephone.gallowdd.pitt.edu/xml/common}agentFilenameXmlEnum"/&gt;
     *         &lt;element name="entry_count" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "agentType",
        "filename",
        "entryCount"
    })
    public static class Agent {

        @XmlElement(name = "agent_type", required = true)
        @XmlSchemaType(name = "string")
        protected AgentDatatypeXmlEnum agentType;
        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected AgentFilenameXmlEnum filename;
        @XmlElement(name = "entry_count", required = true)
        protected BigInteger entryCount;

        /**
         * Gets the value of the agentType property.
         * 
         * @return
         *     possible object is
         *     {@link AgentDatatypeXmlEnum }
         *     
         */
        public AgentDatatypeXmlEnum getAgentType() {
            return agentType;
        }

        /**
         * Sets the value of the agentType property.
         * 
         * @param value
         *     allowed object is
         *     {@link AgentDatatypeXmlEnum }
         *     
         */
        public void setAgentType(AgentDatatypeXmlEnum value) {
            this.agentType = value;
        }

        /**
         * Gets the value of the filename property.
         * 
         * @return
         *     possible object is
         *     {@link AgentFilenameXmlEnum }
         *     
         */
        public AgentFilenameXmlEnum getFilename() {
            return filename;
        }

        /**
         * Sets the value of the filename property.
         * 
         * @param value
         *     allowed object is
         *     {@link AgentFilenameXmlEnum }
         *     
         */
        public void setFilename(AgentFilenameXmlEnum value) {
            this.filename = value;
        }

        /**
         * Gets the value of the entryCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getEntryCount() {
            return entryCount;
        }

        /**
         * Sets the value of the entryCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setEntryCount(BigInteger value) {
            this.entryCount = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="location_type" type="{http://persephone.gallowdd.pitt.edu/xml/common}locationDatatypeXmlEnum"/&gt;
     *         &lt;element name="filename" type="{http://persephone.gallowdd.pitt.edu/xml/common}locationFilenameXmlEnum"/&gt;
     *         &lt;element name="entry_count" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "locationType",
        "filename",
        "entryCount"
    })
    public static class Location {

        @XmlElement(name = "location_type", required = true)
        @XmlSchemaType(name = "string")
        protected LocationDatatypeXmlEnum locationType;
        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected LocationFilenameXmlEnum filename;
        @XmlElement(name = "entry_count", required = true)
        protected BigInteger entryCount;

        /**
         * Gets the value of the locationType property.
         * 
         * @return
         *     possible object is
         *     {@link LocationDatatypeXmlEnum }
         *     
         */
        public LocationDatatypeXmlEnum getLocationType() {
            return locationType;
        }

        /**
         * Sets the value of the locationType property.
         * 
         * @param value
         *     allowed object is
         *     {@link LocationDatatypeXmlEnum }
         *     
         */
        public void setLocationType(LocationDatatypeXmlEnum value) {
            this.locationType = value;
        }

        /**
         * Gets the value of the filename property.
         * 
         * @return
         *     possible object is
         *     {@link LocationFilenameXmlEnum }
         *     
         */
        public LocationFilenameXmlEnum getFilename() {
            return filename;
        }

        /**
         * Sets the value of the filename property.
         * 
         * @param value
         *     allowed object is
         *     {@link LocationFilenameXmlEnum }
         *     
         */
        public void setFilename(LocationFilenameXmlEnum value) {
            this.filename = value;
        }

        /**
         * Gets the value of the entryCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getEntryCount() {
            return entryCount;
        }

        /**
         * Sets the value of the entryCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setEntryCount(BigInteger value) {
            this.entryCount = value;
        }

    }

}
