//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:27 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.common;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for comparisonOperatorTypeXmlEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="comparisonOperatorTypeXmlEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="gt"/&gt;
 *     &lt;enumeration value="lt"/&gt;
 *     &lt;enumeration value="eq"/&gt;
 *     &lt;enumeration value="ne"/&gt;
 *     &lt;enumeration value="gte"/&gt;
 *     &lt;enumeration value="lte"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "comparisonOperatorTypeXmlEnum")
@XmlEnum
public enum ComparisonOperatorTypeXmlEnum {

    @XmlEnumValue("gt")
    GT("gt"),
    @XmlEnumValue("lt")
    LT("lt"),
    @XmlEnumValue("eq")
    EQ("eq"),
    @XmlEnumValue("ne")
    NE("ne"),
    @XmlEnumValue("gte")
    GTE("gte"),
    @XmlEnumValue("lte")
    LTE("lte");
    private final String value;

    ComparisonOperatorTypeXmlEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ComparisonOperatorTypeXmlEnum fromValue(String v) {
        for (ComparisonOperatorTypeXmlEnum c: ComparisonOperatorTypeXmlEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
