//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:27 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.common;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ifStatementXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ifStatementXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="left_operand" type="{http://persephone.gallowdd.pitt.edu/xml/common}operandXmlType"/&gt;
 *         &lt;element name="comparison_operator" type="{http://persephone.gallowdd.pitt.edu/xml/common}comparisonOperatorTypeXmlEnum"/&gt;
 *         &lt;element name="right_operand" type="{http://persephone.gallowdd.pitt.edu/xml/common}operandXmlType"/&gt;
 *         &lt;element name="logical_expression" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="operator" type="{http://persephone.gallowdd.pitt.edu/xml/common}logicalOperatorTypeXmlEnum"/&gt;
 *                   &lt;element name="if" type="{http://persephone.gallowdd.pitt.edu/xml/common}ifStatementXmlType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ifStatementXmlType", propOrder = {
    "leftOperand",
    "comparisonOperator",
    "rightOperand",
    "logicalExpression"
})
public class IfStatementXmlType {

    @XmlElement(name = "left_operand", required = true)
    protected OperandXmlType leftOperand;
    @XmlElement(name = "comparison_operator", required = true)
    @XmlSchemaType(name = "string")
    protected ComparisonOperatorTypeXmlEnum comparisonOperator;
    @XmlElement(name = "right_operand", required = true)
    protected OperandXmlType rightOperand;
    @XmlElement(name = "logical_expression")
    protected List<IfStatementXmlType.LogicalExpression> logicalExpression;

    /**
     * Gets the value of the leftOperand property.
     * 
     * @return
     *     possible object is
     *     {@link OperandXmlType }
     *     
     */
    public OperandXmlType getLeftOperand() {
        return leftOperand;
    }

    /**
     * Sets the value of the leftOperand property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperandXmlType }
     *     
     */
    public void setLeftOperand(OperandXmlType value) {
        this.leftOperand = value;
    }

    /**
     * Gets the value of the comparisonOperator property.
     * 
     * @return
     *     possible object is
     *     {@link ComparisonOperatorTypeXmlEnum }
     *     
     */
    public ComparisonOperatorTypeXmlEnum getComparisonOperator() {
        return comparisonOperator;
    }

    /**
     * Sets the value of the comparisonOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComparisonOperatorTypeXmlEnum }
     *     
     */
    public void setComparisonOperator(ComparisonOperatorTypeXmlEnum value) {
        this.comparisonOperator = value;
    }

    /**
     * Gets the value of the rightOperand property.
     * 
     * @return
     *     possible object is
     *     {@link OperandXmlType }
     *     
     */
    public OperandXmlType getRightOperand() {
        return rightOperand;
    }

    /**
     * Sets the value of the rightOperand property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperandXmlType }
     *     
     */
    public void setRightOperand(OperandXmlType value) {
        this.rightOperand = value;
    }

    /**
     * Gets the value of the logicalExpression property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the logicalExpression property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLogicalExpression().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IfStatementXmlType.LogicalExpression }
     * 
     * 
     */
    public List<IfStatementXmlType.LogicalExpression> getLogicalExpression() {
        if (logicalExpression == null) {
            logicalExpression = new ArrayList<IfStatementXmlType.LogicalExpression>();
        }
        return this.logicalExpression;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="operator" type="{http://persephone.gallowdd.pitt.edu/xml/common}logicalOperatorTypeXmlEnum"/&gt;
     *         &lt;element name="if" type="{http://persephone.gallowdd.pitt.edu/xml/common}ifStatementXmlType"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "operator",
        "_if"
    })
    public static class LogicalExpression {

        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected LogicalOperatorTypeXmlEnum operator;
        @XmlElement(name = "if", required = true)
        protected IfStatementXmlType _if;

        /**
         * Gets the value of the operator property.
         * 
         * @return
         *     possible object is
         *     {@link LogicalOperatorTypeXmlEnum }
         *     
         */
        public LogicalOperatorTypeXmlEnum getOperator() {
            return operator;
        }

        /**
         * Sets the value of the operator property.
         * 
         * @param value
         *     allowed object is
         *     {@link LogicalOperatorTypeXmlEnum }
         *     
         */
        public void setOperator(LogicalOperatorTypeXmlEnum value) {
            this.operator = value;
        }

        /**
         * Gets the value of the if property.
         * 
         * @return
         *     possible object is
         *     {@link IfStatementXmlType }
         *     
         */
        public IfStatementXmlType getIf() {
            return _if;
        }

        /**
         * Sets the value of the if property.
         * 
         * @param value
         *     allowed object is
         *     {@link IfStatementXmlType }
         *     
         */
        public void setIf(IfStatementXmlType value) {
            this._if = value;
        }

    }

}
