//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:27 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.common;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for locationDatatypeXmlEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="locationDatatypeXmlEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Household"/&gt;
 *     &lt;enumeration value="Workplace"/&gt;
 *     &lt;enumeration value="School"/&gt;
 *     &lt;enumeration value="CollegeDorm"/&gt;
 *     &lt;enumeration value="Prison"/&gt;
 *     &lt;enumeration value="NursingFacility"/&gt;
 *     &lt;enumeration value="MilitaryBarracks"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "locationDatatypeXmlEnum")
@XmlEnum
public enum LocationDatatypeXmlEnum {

    @XmlEnumValue("Household")
    HOUSEHOLD("Household"),
    @XmlEnumValue("Workplace")
    WORKPLACE("Workplace"),
    @XmlEnumValue("School")
    SCHOOL("School"),
    @XmlEnumValue("CollegeDorm")
    COLLEGE_DORM("CollegeDorm"),
    @XmlEnumValue("Prison")
    PRISON("Prison"),
    @XmlEnumValue("NursingFacility")
    NURSING_FACILITY("NursingFacility"),
    @XmlEnumValue("MilitaryBarracks")
    MILITARY_BARRACKS("MilitaryBarracks");
    private final String value;

    LocationDatatypeXmlEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LocationDatatypeXmlEnum fromValue(String v) {
        for (LocationDatatypeXmlEnum c: LocationDatatypeXmlEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
