//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:27 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.common;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for logicalOperatorTypeXmlEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="logicalOperatorTypeXmlEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="or"/&gt;
 *     &lt;enumeration value="and"/&gt;
 *     &lt;enumeration value="not"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "logicalOperatorTypeXmlEnum")
@XmlEnum
public enum LogicalOperatorTypeXmlEnum {

    @XmlEnumValue("or")
    OR("or"),
    @XmlEnumValue("and")
    AND("and"),
    @XmlEnumValue("not")
    NOT("not");
    private final String value;

    LogicalOperatorTypeXmlEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LogicalOperatorTypeXmlEnum fromValue(String v) {
        for (LogicalOperatorTypeXmlEnum c: LogicalOperatorTypeXmlEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
