//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:27 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.common;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mathematicalUnaryOperatorTypeXmlEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="mathematicalUnaryOperatorTypeXmlEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="exp"/&gt;
 *     &lt;enumeration value="log"/&gt;
 *     &lt;enumeration value="sqrt"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "mathematicalUnaryOperatorTypeXmlEnum")
@XmlEnum
public enum MathematicalUnaryOperatorTypeXmlEnum {

    @XmlEnumValue("exp")
    EXP("exp"),
    @XmlEnumValue("log")
    LOG("log"),
    @XmlEnumValue("sqrt")
    SQRT("sqrt");
    private final String value;

    MathematicalUnaryOperatorTypeXmlEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MathematicalUnaryOperatorTypeXmlEnum fromValue(String v) {
        for (MathematicalUnaryOperatorTypeXmlEnum c: MathematicalUnaryOperatorTypeXmlEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
