//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:27 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.common;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mathematicalBinaryOperatorTypeXmlEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="mathematicalBinaryOperatorTypeXmlEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="add"/&gt;
 *     &lt;enumeration value="sub"/&gt;
 *     &lt;enumeration value="mult"/&gt;
 *     &lt;enumeration value="div"/&gt;
 *     &lt;enumeration value="mod"/&gt;
 *     &lt;enumeration value="pow"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "mathematicalBinaryOperatorTypeXmlEnum")
@XmlEnum
public enum MathematicalBinaryOperatorTypeXmlEnum {

    @XmlEnumValue("add")
    ADD("add"),
    @XmlEnumValue("sub")
    SUB("sub"),
    @XmlEnumValue("mult")
    MULT("mult"),
    @XmlEnumValue("div")
    DIV("div"),
    @XmlEnumValue("mod")
    MOD("mod"),
    @XmlEnumValue("pow")
    POW("pow");
    private final String value;

    MathematicalBinaryOperatorTypeXmlEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MathematicalBinaryOperatorTypeXmlEnum fromValue(String v) {
        for (MathematicalBinaryOperatorTypeXmlEnum c: MathematicalBinaryOperatorTypeXmlEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
