//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:27 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.common;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.pitt.gallowdd.persephone.xml.common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.pitt.gallowdd.persephone.xml.common
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DistributionXmlType }
     * 
     */
    public DistributionXmlType createDistributionXmlType() {
        return new DistributionXmlType();
    }

    /**
     * Create an instance of {@link OperandXmlType }
     * 
     */
    public OperandXmlType createOperandXmlType() {
        return new OperandXmlType();
    }

    /**
     * Create an instance of {@link IfStatementXmlType }
     * 
     */
    public IfStatementXmlType createIfStatementXmlType() {
        return new IfStatementXmlType();
    }

    /**
     * Create an instance of {@link DynamicFunctionXmlType }
     * 
     */
    public DynamicFunctionXmlType createDynamicFunctionXmlType() {
        return new DynamicFunctionXmlType();
    }

    /**
     * Create an instance of {@link ConditionXmlType }
     * 
     */
    public ConditionXmlType createConditionXmlType() {
        return new ConditionXmlType();
    }

    /**
     * Create an instance of {@link ConditionXmlType.State }
     * 
     */
    public ConditionXmlType.State createConditionXmlTypeState() {
        return new ConditionXmlType.State();
    }

    /**
     * Create an instance of {@link ConditionXmlType.State.TransitionRule }
     * 
     */
    public ConditionXmlType.State.TransitionRule createConditionXmlTypeStateTransitionRule() {
        return new ConditionXmlType.State.TransitionRule();
    }

    /**
     * Create an instance of {@link UnaryNumericalOperationXmlType }
     * 
     */
    public UnaryNumericalOperationXmlType createUnaryNumericalOperationXmlType() {
        return new UnaryNumericalOperationXmlType();
    }

    /**
     * Create an instance of {@link BinaryNumericalOperationXmlType }
     * 
     */
    public BinaryNumericalOperationXmlType createBinaryNumericalOperationXmlType() {
        return new BinaryNumericalOperationXmlType();
    }

    /**
     * Create an instance of {@link DistributionXmlType.Normal }
     * 
     */
    public DistributionXmlType.Normal createDistributionXmlTypeNormal() {
        return new DistributionXmlType.Normal();
    }

    /**
     * Create an instance of {@link DistributionXmlType.Lognormal }
     * 
     */
    public DistributionXmlType.Lognormal createDistributionXmlTypeLognormal() {
        return new DistributionXmlType.Lognormal();
    }

    /**
     * Create an instance of {@link DistributionXmlType.Uniform }
     * 
     */
    public DistributionXmlType.Uniform createDistributionXmlTypeUniform() {
        return new DistributionXmlType.Uniform();
    }

    /**
     * Create an instance of {@link DistributionXmlType.Exponential }
     * 
     */
    public DistributionXmlType.Exponential createDistributionXmlTypeExponential() {
        return new DistributionXmlType.Exponential();
    }

    /**
     * Create an instance of {@link OperandXmlType.ConstantValue }
     * 
     */
    public OperandXmlType.ConstantValue createOperandXmlTypeConstantValue() {
        return new OperandXmlType.ConstantValue();
    }

    /**
     * Create an instance of {@link IfStatementXmlType.LogicalExpression }
     * 
     */
    public IfStatementXmlType.LogicalExpression createIfStatementXmlTypeLogicalExpression() {
        return new IfStatementXmlType.LogicalExpression();
    }

    /**
     * Create an instance of {@link DynamicFunctionXmlType.Parameters }
     * 
     */
    public DynamicFunctionXmlType.Parameters createDynamicFunctionXmlTypeParameters() {
        return new DynamicFunctionXmlType.Parameters();
    }

    /**
     * Create an instance of {@link ConditionXmlType.State.WaitRule }
     * 
     */
    public ConditionXmlType.State.WaitRule createConditionXmlTypeStateWaitRule() {
        return new ConditionXmlType.State.WaitRule();
    }

    /**
     * Create an instance of {@link ConditionXmlType.State.TransitionRule.Resolver }
     * 
     */
    public ConditionXmlType.State.TransitionRule.Resolver createConditionXmlTypeStateTransitionRuleResolver() {
        return new ConditionXmlType.State.TransitionRule.Resolver();
    }

}
