//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:27 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.common;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for unaryNumericalOperationXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="unaryNumericalOperationXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="operand" type="{http://persephone.gallowdd.pitt.edu/xml/common}operandXmlType"/&gt;
 *         &lt;element name="operator" type="{http://persephone.gallowdd.pitt.edu/xml/common}mathematicalUnaryOperatorTypeXmlEnum"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "unaryNumericalOperationXmlType", propOrder = {
    "operand",
    "operator"
})
public class UnaryNumericalOperationXmlType {

    @XmlElement(required = true)
    protected OperandXmlType operand;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected MathematicalUnaryOperatorTypeXmlEnum operator;

    /**
     * Gets the value of the operand property.
     * 
     * @return
     *     possible object is
     *     {@link OperandXmlType }
     *     
     */
    public OperandXmlType getOperand() {
        return operand;
    }

    /**
     * Sets the value of the operand property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperandXmlType }
     *     
     */
    public void setOperand(OperandXmlType value) {
        this.operand = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link MathematicalUnaryOperatorTypeXmlEnum }
     *     
     */
    public MathematicalUnaryOperatorTypeXmlEnum getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MathematicalUnaryOperatorTypeXmlEnum }
     *     
     */
    public void setOperator(MathematicalUnaryOperatorTypeXmlEnum value) {
        this.operator = value;
    }

}
