//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:18 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.runtime;

import java.util.ArrayList;
import java.util.List;
import edu.pitt.gallowdd.persephone.xml.common.ConditionXmlType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for modelXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="modelXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="user_defined_agent" type="{http://persephone.gallowdd.pitt.edu/xml/runtime}userDefinedAgentXmlType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="user_defined_location" type="{http://persephone.gallowdd.pitt.edu/xml/runtime}userDefinedLocationXmlType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="user_defined_network" type="{http://persephone.gallowdd.pitt.edu/xml/runtime}userDefinedNetworkXmlType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="condition" type="{http://persephone.gallowdd.pitt.edu/xml/common}conditionXmlType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "modelXmlType", propOrder = {
    "userDefinedAgent",
    "userDefinedLocation",
    "userDefinedNetwork",
    "condition"
})
public class ModelXmlType {

    @XmlElement(name = "user_defined_agent")
    protected List<UserDefinedAgentXmlType> userDefinedAgent;
    @XmlElement(name = "user_defined_location")
    protected List<UserDefinedLocationXmlType> userDefinedLocation;
    @XmlElement(name = "user_defined_network")
    protected List<UserDefinedNetworkXmlType> userDefinedNetwork;
    @XmlElement(required = true)
    protected List<ConditionXmlType> condition;

    /**
     * Gets the value of the userDefinedAgent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the userDefinedAgent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserDefinedAgent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserDefinedAgentXmlType }
     * 
     * 
     */
    public List<UserDefinedAgentXmlType> getUserDefinedAgent() {
        if (userDefinedAgent == null) {
            userDefinedAgent = new ArrayList<UserDefinedAgentXmlType>();
        }
        return this.userDefinedAgent;
    }

    /**
     * Gets the value of the userDefinedLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the userDefinedLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserDefinedLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserDefinedLocationXmlType }
     * 
     * 
     */
    public List<UserDefinedLocationXmlType> getUserDefinedLocation() {
        if (userDefinedLocation == null) {
            userDefinedLocation = new ArrayList<UserDefinedLocationXmlType>();
        }
        return this.userDefinedLocation;
    }

    /**
     * Gets the value of the userDefinedNetwork property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the userDefinedNetwork property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserDefinedNetwork().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserDefinedNetworkXmlType }
     * 
     * 
     */
    public List<UserDefinedNetworkXmlType> getUserDefinedNetwork() {
        if (userDefinedNetwork == null) {
            userDefinedNetwork = new ArrayList<UserDefinedNetworkXmlType>();
        }
        return this.userDefinedNetwork;
    }

    /**
     * Gets the value of the condition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the condition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConditionXmlType }
     * 
     * 
     */
    public List<ConditionXmlType> getCondition() {
        if (condition == null) {
            condition = new ArrayList<ConditionXmlType>();
        }
        return this.condition;
    }

}
