//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:18 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.runtime;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="simulation" type="{http://persephone.gallowdd.pitt.edu/xml/runtime}simulationXmlType"/&gt;
 *         &lt;element name="model" type="{http://persephone.gallowdd.pitt.edu/xml/runtime}modelXmlType"/&gt;
 *         &lt;element name="message_queue" type="{http://persephone.gallowdd.pitt.edu/xml/runtime}messageQueuingXmlType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "simulation",
    "model",
    "messageQueue"
})
@XmlRootElement(name = "persephone_runtime_parameters")
public class PersephoneRuntimeParameters {

    @XmlElement(required = true)
    protected SimulationXmlType simulation;
    @XmlElement(required = true)
    protected ModelXmlType model;
    @XmlElement(name = "message_queue")
    protected MessageQueuingXmlType messageQueue;

    /**
     * Gets the value of the simulation property.
     * 
     * @return
     *     possible object is
     *     {@link SimulationXmlType }
     *     
     */
    public SimulationXmlType getSimulation() {
        return simulation;
    }

    /**
     * Sets the value of the simulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimulationXmlType }
     *     
     */
    public void setSimulation(SimulationXmlType value) {
        this.simulation = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link ModelXmlType }
     *     
     */
    public ModelXmlType getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelXmlType }
     *     
     */
    public void setModel(ModelXmlType value) {
        this.model = value;
    }

    /**
     * Gets the value of the messageQueue property.
     * 
     * @return
     *     possible object is
     *     {@link MessageQueuingXmlType }
     *     
     */
    public MessageQueuingXmlType getMessageQueue() {
        return messageQueue;
    }

    /**
     * Sets the value of the messageQueue property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageQueuingXmlType }
     *     
     */
    public void setMessageQueue(MessageQueuingXmlType value) {
        this.messageQueue = value;
    }

}
