//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:18 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.runtime;

import java.util.ArrayList;
import java.util.List;
import edu.pitt.gallowdd.persephone.xml.common.DatatypeXmlEnum;
import edu.pitt.gallowdd.persephone.xml.common.DistributionXmlType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for userDefinedLocationXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userDefinedLocationXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="latitude"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="initial_file"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="link_file"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="random_generation" type="{http://persephone.gallowdd.pitt.edu/xml/common}distributionXmlType"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="longitude"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="initial_file"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="link_file"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="random_generation" type="{http://persephone.gallowdd.pitt.edu/xml/common}distributionXmlType"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="elevation" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="initial_file"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="link_file"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="random_generation" type="{http://persephone.gallowdd.pitt.edu/xml/common}distributionXmlType"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="location_attribute" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="data_type" type="{http://persephone.gallowdd.pitt.edu/xml/common}datatypeXmlEnum"/&gt;
 *                   &lt;element name="source" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="initial_file"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="link"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="attr_name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userDefinedLocationXmlType", propOrder = {
    "latitude",
    "longitude",
    "elevation",
    "locationAttribute"
})
public class UserDefinedLocationXmlType {

    @XmlElement(required = true)
    protected UserDefinedLocationXmlType.Latitude latitude;
    @XmlElement(required = true)
    protected UserDefinedLocationXmlType.Longitude longitude;
    protected UserDefinedLocationXmlType.Elevation elevation;
    @XmlElement(name = "location_attribute")
    protected List<UserDefinedLocationXmlType.LocationAttribute> locationAttribute;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedLocationXmlType.Latitude }
     *     
     */
    public UserDefinedLocationXmlType.Latitude getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedLocationXmlType.Latitude }
     *     
     */
    public void setLatitude(UserDefinedLocationXmlType.Latitude value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedLocationXmlType.Longitude }
     *     
     */
    public UserDefinedLocationXmlType.Longitude getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedLocationXmlType.Longitude }
     *     
     */
    public void setLongitude(UserDefinedLocationXmlType.Longitude value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the elevation property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedLocationXmlType.Elevation }
     *     
     */
    public UserDefinedLocationXmlType.Elevation getElevation() {
        return elevation;
    }

    /**
     * Sets the value of the elevation property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedLocationXmlType.Elevation }
     *     
     */
    public void setElevation(UserDefinedLocationXmlType.Elevation value) {
        this.elevation = value;
    }

    /**
     * Gets the value of the locationAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the locationAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocationAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserDefinedLocationXmlType.LocationAttribute }
     * 
     * 
     */
    public List<UserDefinedLocationXmlType.LocationAttribute> getLocationAttribute() {
        if (locationAttribute == null) {
            locationAttribute = new ArrayList<UserDefinedLocationXmlType.LocationAttribute>();
        }
        return this.locationAttribute;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="initial_file"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="link_file"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="random_generation" type="{http://persephone.gallowdd.pitt.edu/xml/common}distributionXmlType"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "initialFile",
        "linkFile",
        "randomGeneration"
    })
    public static class Elevation {

        @XmlElement(name = "initial_file")
        protected UserDefinedLocationXmlType.Elevation.InitialFile initialFile;
        @XmlElement(name = "link_file")
        protected UserDefinedLocationXmlType.Elevation.LinkFile linkFile;
        @XmlElement(name = "random_generation")
        protected DistributionXmlType randomGeneration;

        /**
         * Gets the value of the initialFile property.
         * 
         * @return
         *     possible object is
         *     {@link UserDefinedLocationXmlType.Elevation.InitialFile }
         *     
         */
        public UserDefinedLocationXmlType.Elevation.InitialFile getInitialFile() {
            return initialFile;
        }

        /**
         * Sets the value of the initialFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link UserDefinedLocationXmlType.Elevation.InitialFile }
         *     
         */
        public void setInitialFile(UserDefinedLocationXmlType.Elevation.InitialFile value) {
            this.initialFile = value;
        }

        /**
         * Gets the value of the linkFile property.
         * 
         * @return
         *     possible object is
         *     {@link UserDefinedLocationXmlType.Elevation.LinkFile }
         *     
         */
        public UserDefinedLocationXmlType.Elevation.LinkFile getLinkFile() {
            return linkFile;
        }

        /**
         * Sets the value of the linkFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link UserDefinedLocationXmlType.Elevation.LinkFile }
         *     
         */
        public void setLinkFile(UserDefinedLocationXmlType.Elevation.LinkFile value) {
            this.linkFile = value;
        }

        /**
         * Gets the value of the randomGeneration property.
         * 
         * @return
         *     possible object is
         *     {@link DistributionXmlType }
         *     
         */
        public DistributionXmlType getRandomGeneration() {
            return randomGeneration;
        }

        /**
         * Sets the value of the randomGeneration property.
         * 
         * @param value
         *     allowed object is
         *     {@link DistributionXmlType }
         *     
         */
        public void setRandomGeneration(DistributionXmlType value) {
            this.randomGeneration = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dir",
            "filename",
            "csvFieldName"
        })
        public static class InitialFile {

            @XmlElement(required = true)
            protected String dir;
            @XmlElement(required = true)
            protected String filename;
            @XmlElement(name = "csv_field_name", required = true)
            protected String csvFieldName;

            /**
             * Gets the value of the dir property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDir() {
                return dir;
            }

            /**
             * Sets the value of the dir property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDir(String value) {
                this.dir = value;
            }

            /**
             * Gets the value of the filename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFilename() {
                return filename;
            }

            /**
             * Sets the value of the filename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFilename(String value) {
                this.filename = value;
            }

            /**
             * Gets the value of the csvFieldName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCsvFieldName() {
                return csvFieldName;
            }

            /**
             * Sets the value of the csvFieldName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCsvFieldName(String value) {
                this.csvFieldName = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dir",
            "filename",
            "csvFieldName"
        })
        public static class LinkFile {

            @XmlElement(required = true)
            protected String dir;
            @XmlElement(required = true)
            protected String filename;
            @XmlElement(name = "csv_field_name", required = true)
            protected String csvFieldName;

            /**
             * Gets the value of the dir property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDir() {
                return dir;
            }

            /**
             * Sets the value of the dir property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDir(String value) {
                this.dir = value;
            }

            /**
             * Gets the value of the filename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFilename() {
                return filename;
            }

            /**
             * Sets the value of the filename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFilename(String value) {
                this.filename = value;
            }

            /**
             * Gets the value of the csvFieldName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCsvFieldName() {
                return csvFieldName;
            }

            /**
             * Sets the value of the csvFieldName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCsvFieldName(String value) {
                this.csvFieldName = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="initial_file"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="link_file"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="random_generation" type="{http://persephone.gallowdd.pitt.edu/xml/common}distributionXmlType"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "initialFile",
        "linkFile",
        "randomGeneration"
    })
    public static class Latitude {

        @XmlElement(name = "initial_file")
        protected UserDefinedLocationXmlType.Latitude.InitialFile initialFile;
        @XmlElement(name = "link_file")
        protected UserDefinedLocationXmlType.Latitude.LinkFile linkFile;
        @XmlElement(name = "random_generation")
        protected DistributionXmlType randomGeneration;

        /**
         * Gets the value of the initialFile property.
         * 
         * @return
         *     possible object is
         *     {@link UserDefinedLocationXmlType.Latitude.InitialFile }
         *     
         */
        public UserDefinedLocationXmlType.Latitude.InitialFile getInitialFile() {
            return initialFile;
        }

        /**
         * Sets the value of the initialFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link UserDefinedLocationXmlType.Latitude.InitialFile }
         *     
         */
        public void setInitialFile(UserDefinedLocationXmlType.Latitude.InitialFile value) {
            this.initialFile = value;
        }

        /**
         * Gets the value of the linkFile property.
         * 
         * @return
         *     possible object is
         *     {@link UserDefinedLocationXmlType.Latitude.LinkFile }
         *     
         */
        public UserDefinedLocationXmlType.Latitude.LinkFile getLinkFile() {
            return linkFile;
        }

        /**
         * Sets the value of the linkFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link UserDefinedLocationXmlType.Latitude.LinkFile }
         *     
         */
        public void setLinkFile(UserDefinedLocationXmlType.Latitude.LinkFile value) {
            this.linkFile = value;
        }

        /**
         * Gets the value of the randomGeneration property.
         * 
         * @return
         *     possible object is
         *     {@link DistributionXmlType }
         *     
         */
        public DistributionXmlType getRandomGeneration() {
            return randomGeneration;
        }

        /**
         * Sets the value of the randomGeneration property.
         * 
         * @param value
         *     allowed object is
         *     {@link DistributionXmlType }
         *     
         */
        public void setRandomGeneration(DistributionXmlType value) {
            this.randomGeneration = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dir",
            "filename",
            "csvFieldName"
        })
        public static class InitialFile {

            @XmlElement(required = true)
            protected String dir;
            @XmlElement(required = true)
            protected String filename;
            @XmlElement(name = "csv_field_name", required = true)
            protected String csvFieldName;

            /**
             * Gets the value of the dir property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDir() {
                return dir;
            }

            /**
             * Sets the value of the dir property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDir(String value) {
                this.dir = value;
            }

            /**
             * Gets the value of the filename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFilename() {
                return filename;
            }

            /**
             * Sets the value of the filename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFilename(String value) {
                this.filename = value;
            }

            /**
             * Gets the value of the csvFieldName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCsvFieldName() {
                return csvFieldName;
            }

            /**
             * Sets the value of the csvFieldName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCsvFieldName(String value) {
                this.csvFieldName = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dir",
            "filename",
            "csvFieldName"
        })
        public static class LinkFile {

            @XmlElement(required = true)
            protected String dir;
            @XmlElement(required = true)
            protected String filename;
            @XmlElement(name = "csv_field_name", required = true)
            protected String csvFieldName;

            /**
             * Gets the value of the dir property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDir() {
                return dir;
            }

            /**
             * Sets the value of the dir property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDir(String value) {
                this.dir = value;
            }

            /**
             * Gets the value of the filename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFilename() {
                return filename;
            }

            /**
             * Sets the value of the filename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFilename(String value) {
                this.filename = value;
            }

            /**
             * Gets the value of the csvFieldName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCsvFieldName() {
                return csvFieldName;
            }

            /**
             * Sets the value of the csvFieldName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCsvFieldName(String value) {
                this.csvFieldName = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="data_type" type="{http://persephone.gallowdd.pitt.edu/xml/common}datatypeXmlEnum"/&gt;
     *         &lt;element name="source" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="initial_file"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="link"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="attr_name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataType",
        "source"
    })
    public static class LocationAttribute {

        @XmlElement(name = "data_type", required = true)
        @XmlSchemaType(name = "string")
        protected DatatypeXmlEnum dataType;
        protected UserDefinedLocationXmlType.LocationAttribute.Source source;
        @XmlAttribute(name = "attr_name", required = true)
        protected String attrName;

        /**
         * Gets the value of the dataType property.
         * 
         * @return
         *     possible object is
         *     {@link DatatypeXmlEnum }
         *     
         */
        public DatatypeXmlEnum getDataType() {
            return dataType;
        }

        /**
         * Sets the value of the dataType property.
         * 
         * @param value
         *     allowed object is
         *     {@link DatatypeXmlEnum }
         *     
         */
        public void setDataType(DatatypeXmlEnum value) {
            this.dataType = value;
        }

        /**
         * Gets the value of the source property.
         * 
         * @return
         *     possible object is
         *     {@link UserDefinedLocationXmlType.LocationAttribute.Source }
         *     
         */
        public UserDefinedLocationXmlType.LocationAttribute.Source getSource() {
            return source;
        }

        /**
         * Sets the value of the source property.
         * 
         * @param value
         *     allowed object is
         *     {@link UserDefinedLocationXmlType.LocationAttribute.Source }
         *     
         */
        public void setSource(UserDefinedLocationXmlType.LocationAttribute.Source value) {
            this.source = value;
        }

        /**
         * Gets the value of the attrName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttrName() {
            return attrName;
        }

        /**
         * Sets the value of the attrName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttrName(String value) {
            this.attrName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="initial_file"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="link"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "initialFile",
            "link"
        })
        public static class Source {

            @XmlElement(name = "initial_file")
            protected UserDefinedLocationXmlType.LocationAttribute.Source.InitialFile initialFile;
            protected UserDefinedLocationXmlType.LocationAttribute.Source.Link link;

            /**
             * Gets the value of the initialFile property.
             * 
             * @return
             *     possible object is
             *     {@link UserDefinedLocationXmlType.LocationAttribute.Source.InitialFile }
             *     
             */
            public UserDefinedLocationXmlType.LocationAttribute.Source.InitialFile getInitialFile() {
                return initialFile;
            }

            /**
             * Sets the value of the initialFile property.
             * 
             * @param value
             *     allowed object is
             *     {@link UserDefinedLocationXmlType.LocationAttribute.Source.InitialFile }
             *     
             */
            public void setInitialFile(UserDefinedLocationXmlType.LocationAttribute.Source.InitialFile value) {
                this.initialFile = value;
            }

            /**
             * Gets the value of the link property.
             * 
             * @return
             *     possible object is
             *     {@link UserDefinedLocationXmlType.LocationAttribute.Source.Link }
             *     
             */
            public UserDefinedLocationXmlType.LocationAttribute.Source.Link getLink() {
                return link;
            }

            /**
             * Sets the value of the link property.
             * 
             * @param value
             *     allowed object is
             *     {@link UserDefinedLocationXmlType.LocationAttribute.Source.Link }
             *     
             */
            public void setLink(UserDefinedLocationXmlType.LocationAttribute.Source.Link value) {
                this.link = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "dir",
                "filename",
                "csvFieldName"
            })
            public static class InitialFile {

                @XmlElement(required = true)
                protected String dir;
                @XmlElement(required = true)
                protected String filename;
                @XmlElement(name = "csv_field_name", required = true)
                protected String csvFieldName;

                /**
                 * Gets the value of the dir property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDir() {
                    return dir;
                }

                /**
                 * Sets the value of the dir property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDir(String value) {
                    this.dir = value;
                }

                /**
                 * Gets the value of the filename property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFilename() {
                    return filename;
                }

                /**
                 * Sets the value of the filename property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFilename(String value) {
                    this.filename = value;
                }

                /**
                 * Gets the value of the csvFieldName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCsvFieldName() {
                    return csvFieldName;
                }

                /**
                 * Sets the value of the csvFieldName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCsvFieldName(String value) {
                    this.csvFieldName = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "dir",
                "filename",
                "csvFieldName"
            })
            public static class Link {

                @XmlElement(required = true)
                protected String dir;
                @XmlElement(required = true)
                protected String filename;
                @XmlElement(name = "csv_field_name", required = true)
                protected String csvFieldName;

                /**
                 * Gets the value of the dir property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDir() {
                    return dir;
                }

                /**
                 * Sets the value of the dir property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDir(String value) {
                    this.dir = value;
                }

                /**
                 * Gets the value of the filename property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFilename() {
                    return filename;
                }

                /**
                 * Sets the value of the filename property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFilename(String value) {
                    this.filename = value;
                }

                /**
                 * Gets the value of the csvFieldName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCsvFieldName() {
                    return csvFieldName;
                }

                /**
                 * Sets the value of the csvFieldName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCsvFieldName(String value) {
                    this.csvFieldName = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="initial_file"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="link_file"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="random_generation" type="{http://persephone.gallowdd.pitt.edu/xml/common}distributionXmlType"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "initialFile",
        "linkFile",
        "randomGeneration"
    })
    public static class Longitude {

        @XmlElement(name = "initial_file")
        protected UserDefinedLocationXmlType.Longitude.InitialFile initialFile;
        @XmlElement(name = "link_file")
        protected UserDefinedLocationXmlType.Longitude.LinkFile linkFile;
        @XmlElement(name = "random_generation")
        protected DistributionXmlType randomGeneration;

        /**
         * Gets the value of the initialFile property.
         * 
         * @return
         *     possible object is
         *     {@link UserDefinedLocationXmlType.Longitude.InitialFile }
         *     
         */
        public UserDefinedLocationXmlType.Longitude.InitialFile getInitialFile() {
            return initialFile;
        }

        /**
         * Sets the value of the initialFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link UserDefinedLocationXmlType.Longitude.InitialFile }
         *     
         */
        public void setInitialFile(UserDefinedLocationXmlType.Longitude.InitialFile value) {
            this.initialFile = value;
        }

        /**
         * Gets the value of the linkFile property.
         * 
         * @return
         *     possible object is
         *     {@link UserDefinedLocationXmlType.Longitude.LinkFile }
         *     
         */
        public UserDefinedLocationXmlType.Longitude.LinkFile getLinkFile() {
            return linkFile;
        }

        /**
         * Sets the value of the linkFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link UserDefinedLocationXmlType.Longitude.LinkFile }
         *     
         */
        public void setLinkFile(UserDefinedLocationXmlType.Longitude.LinkFile value) {
            this.linkFile = value;
        }

        /**
         * Gets the value of the randomGeneration property.
         * 
         * @return
         *     possible object is
         *     {@link DistributionXmlType }
         *     
         */
        public DistributionXmlType getRandomGeneration() {
            return randomGeneration;
        }

        /**
         * Sets the value of the randomGeneration property.
         * 
         * @param value
         *     allowed object is
         *     {@link DistributionXmlType }
         *     
         */
        public void setRandomGeneration(DistributionXmlType value) {
            this.randomGeneration = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dir",
            "filename",
            "csvFieldName"
        })
        public static class InitialFile {

            @XmlElement(required = true)
            protected String dir;
            @XmlElement(required = true)
            protected String filename;
            @XmlElement(name = "csv_field_name", required = true)
            protected String csvFieldName;

            /**
             * Gets the value of the dir property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDir() {
                return dir;
            }

            /**
             * Sets the value of the dir property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDir(String value) {
                this.dir = value;
            }

            /**
             * Gets the value of the filename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFilename() {
                return filename;
            }

            /**
             * Sets the value of the filename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFilename(String value) {
                this.filename = value;
            }

            /**
             * Gets the value of the csvFieldName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCsvFieldName() {
                return csvFieldName;
            }

            /**
             * Sets the value of the csvFieldName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCsvFieldName(String value) {
                this.csvFieldName = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="csv_field_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dir",
            "filename",
            "csvFieldName"
        })
        public static class LinkFile {

            @XmlElement(required = true)
            protected String dir;
            @XmlElement(required = true)
            protected String filename;
            @XmlElement(name = "csv_field_name", required = true)
            protected String csvFieldName;

            /**
             * Gets the value of the dir property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDir() {
                return dir;
            }

            /**
             * Sets the value of the dir property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDir(String value) {
                this.dir = value;
            }

            /**
             * Gets the value of the filename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFilename() {
                return filename;
            }

            /**
             * Sets the value of the filename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFilename(String value) {
                this.filename = value;
            }

            /**
             * Gets the value of the csvFieldName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCsvFieldName() {
                return csvFieldName;
            }

            /**
             * Sets the value of the csvFieldName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCsvFieldName(String value) {
                this.csvFieldName = value;
            }

        }

    }

}
