//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.07 at 10:39:30 AM EST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://persephone.gallowdd.pitt.edu/synthenvinfo", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.pitt.gallowdd.persephone.synthenvinfo;
