//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.07 at 10:39:30 AM EST 
//


package edu.pitt.gallowdd.persephone.synthenvinfo;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for popVersionXmlEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="popVersionXmlEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Persephone.v1.0"/&gt;
 *     &lt;enumeration value="other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "popVersionXmlEnum")
@XmlEnum
public enum PopVersionXmlEnum {

    @XmlEnumValue("Persephone.v1.0")
    PERSEPHONE_V_1_0("Persephone.v1.0"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    PopVersionXmlEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PopVersionXmlEnum fromValue(String v) {
        for (PopVersionXmlEnum c: PopVersionXmlEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
