//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:18 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.runtime;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.pitt.gallowdd.persephone.xml.runtime package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.pitt.gallowdd.persephone.xml.runtime
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserDefinedNetworkXmlType }
     * 
     */
    public UserDefinedNetworkXmlType createUserDefinedNetworkXmlType() {
        return new UserDefinedNetworkXmlType();
    }

    /**
     * Create an instance of {@link UserDefinedNetworkXmlType.NetworkAttribute }
     * 
     */
    public UserDefinedNetworkXmlType.NetworkAttribute createUserDefinedNetworkXmlTypeNetworkAttribute() {
        return new UserDefinedNetworkXmlType.NetworkAttribute();
    }

    /**
     * Create an instance of {@link UserDefinedNetworkXmlType.NetworkAttribute.Source }
     * 
     */
    public UserDefinedNetworkXmlType.NetworkAttribute.Source createUserDefinedNetworkXmlTypeNetworkAttributeSource() {
        return new UserDefinedNetworkXmlType.NetworkAttribute.Source();
    }

    /**
     * Create an instance of {@link UserDefinedLocationXmlType }
     * 
     */
    public UserDefinedLocationXmlType createUserDefinedLocationXmlType() {
        return new UserDefinedLocationXmlType();
    }

    /**
     * Create an instance of {@link UserDefinedLocationXmlType.LocationAttribute }
     * 
     */
    public UserDefinedLocationXmlType.LocationAttribute createUserDefinedLocationXmlTypeLocationAttribute() {
        return new UserDefinedLocationXmlType.LocationAttribute();
    }

    /**
     * Create an instance of {@link UserDefinedLocationXmlType.LocationAttribute.Source }
     * 
     */
    public UserDefinedLocationXmlType.LocationAttribute.Source createUserDefinedLocationXmlTypeLocationAttributeSource() {
        return new UserDefinedLocationXmlType.LocationAttribute.Source();
    }

    /**
     * Create an instance of {@link UserDefinedLocationXmlType.Elevation }
     * 
     */
    public UserDefinedLocationXmlType.Elevation createUserDefinedLocationXmlTypeElevation() {
        return new UserDefinedLocationXmlType.Elevation();
    }

    /**
     * Create an instance of {@link UserDefinedLocationXmlType.Longitude }
     * 
     */
    public UserDefinedLocationXmlType.Longitude createUserDefinedLocationXmlTypeLongitude() {
        return new UserDefinedLocationXmlType.Longitude();
    }

    /**
     * Create an instance of {@link UserDefinedLocationXmlType.Latitude }
     * 
     */
    public UserDefinedLocationXmlType.Latitude createUserDefinedLocationXmlTypeLatitude() {
        return new UserDefinedLocationXmlType.Latitude();
    }

    /**
     * Create an instance of {@link UserDefinedAgentXmlType }
     * 
     */
    public UserDefinedAgentXmlType createUserDefinedAgentXmlType() {
        return new UserDefinedAgentXmlType();
    }

    /**
     * Create an instance of {@link UserDefinedAgentXmlType.AgentAttribute }
     * 
     */
    public UserDefinedAgentXmlType.AgentAttribute createUserDefinedAgentXmlTypeAgentAttribute() {
        return new UserDefinedAgentXmlType.AgentAttribute();
    }

    /**
     * Create an instance of {@link UserDefinedAgentXmlType.AgentAttribute.Source }
     * 
     */
    public UserDefinedAgentXmlType.AgentAttribute.Source createUserDefinedAgentXmlTypeAgentAttributeSource() {
        return new UserDefinedAgentXmlType.AgentAttribute.Source();
    }

    /**
     * Create an instance of {@link SimulationXmlType }
     * 
     */
    public SimulationXmlType createSimulationXmlType() {
        return new SimulationXmlType();
    }

    /**
     * Create an instance of {@link PersephoneRuntimeParameters }
     * 
     */
    public PersephoneRuntimeParameters createPersephoneRuntimeParameters() {
        return new PersephoneRuntimeParameters();
    }

    /**
     * Create an instance of {@link ModelXmlType }
     * 
     */
    public ModelXmlType createModelXmlType() {
        return new ModelXmlType();
    }

    /**
     * Create an instance of {@link MessageQueuingXmlType }
     * 
     */
    public MessageQueuingXmlType createMessageQueuingXmlType() {
        return new MessageQueuingXmlType();
    }

    /**
     * Create an instance of {@link UserDefinedNetworkXmlType.NetworkAttribute.Source.InitialFile }
     * 
     */
    public UserDefinedNetworkXmlType.NetworkAttribute.Source.InitialFile createUserDefinedNetworkXmlTypeNetworkAttributeSourceInitialFile() {
        return new UserDefinedNetworkXmlType.NetworkAttribute.Source.InitialFile();
    }

    /**
     * Create an instance of {@link UserDefinedNetworkXmlType.NetworkAttribute.Source.Link }
     * 
     */
    public UserDefinedNetworkXmlType.NetworkAttribute.Source.Link createUserDefinedNetworkXmlTypeNetworkAttributeSourceLink() {
        return new UserDefinedNetworkXmlType.NetworkAttribute.Source.Link();
    }

    /**
     * Create an instance of {@link UserDefinedLocationXmlType.LocationAttribute.Source.InitialFile }
     * 
     */
    public UserDefinedLocationXmlType.LocationAttribute.Source.InitialFile createUserDefinedLocationXmlTypeLocationAttributeSourceInitialFile() {
        return new UserDefinedLocationXmlType.LocationAttribute.Source.InitialFile();
    }

    /**
     * Create an instance of {@link UserDefinedLocationXmlType.LocationAttribute.Source.Link }
     * 
     */
    public UserDefinedLocationXmlType.LocationAttribute.Source.Link createUserDefinedLocationXmlTypeLocationAttributeSourceLink() {
        return new UserDefinedLocationXmlType.LocationAttribute.Source.Link();
    }

    /**
     * Create an instance of {@link UserDefinedLocationXmlType.Elevation.InitialFile }
     * 
     */
    public UserDefinedLocationXmlType.Elevation.InitialFile createUserDefinedLocationXmlTypeElevationInitialFile() {
        return new UserDefinedLocationXmlType.Elevation.InitialFile();
    }

    /**
     * Create an instance of {@link UserDefinedLocationXmlType.Elevation.LinkFile }
     * 
     */
    public UserDefinedLocationXmlType.Elevation.LinkFile createUserDefinedLocationXmlTypeElevationLinkFile() {
        return new UserDefinedLocationXmlType.Elevation.LinkFile();
    }

    /**
     * Create an instance of {@link UserDefinedLocationXmlType.Longitude.InitialFile }
     * 
     */
    public UserDefinedLocationXmlType.Longitude.InitialFile createUserDefinedLocationXmlTypeLongitudeInitialFile() {
        return new UserDefinedLocationXmlType.Longitude.InitialFile();
    }

    /**
     * Create an instance of {@link UserDefinedLocationXmlType.Longitude.LinkFile }
     * 
     */
    public UserDefinedLocationXmlType.Longitude.LinkFile createUserDefinedLocationXmlTypeLongitudeLinkFile() {
        return new UserDefinedLocationXmlType.Longitude.LinkFile();
    }

    /**
     * Create an instance of {@link UserDefinedLocationXmlType.Latitude.InitialFile }
     * 
     */
    public UserDefinedLocationXmlType.Latitude.InitialFile createUserDefinedLocationXmlTypeLatitudeInitialFile() {
        return new UserDefinedLocationXmlType.Latitude.InitialFile();
    }

    /**
     * Create an instance of {@link UserDefinedLocationXmlType.Latitude.LinkFile }
     * 
     */
    public UserDefinedLocationXmlType.Latitude.LinkFile createUserDefinedLocationXmlTypeLatitudeLinkFile() {
        return new UserDefinedLocationXmlType.Latitude.LinkFile();
    }

    /**
     * Create an instance of {@link UserDefinedAgentXmlType.AgentAttribute.Source.InitialFile }
     * 
     */
    public UserDefinedAgentXmlType.AgentAttribute.Source.InitialFile createUserDefinedAgentXmlTypeAgentAttributeSourceInitialFile() {
        return new UserDefinedAgentXmlType.AgentAttribute.Source.InitialFile();
    }

    /**
     * Create an instance of {@link UserDefinedAgentXmlType.AgentAttribute.Source.LinkFile }
     * 
     */
    public UserDefinedAgentXmlType.AgentAttribute.Source.LinkFile createUserDefinedAgentXmlTypeAgentAttributeSourceLinkFile() {
        return new UserDefinedAgentXmlType.AgentAttribute.Source.LinkFile();
    }

    /**
     * Create an instance of {@link SimulationXmlType.SyntheticEnvironmentDescriptor }
     * 
     */
    public SimulationXmlType.SyntheticEnvironmentDescriptor createSimulationXmlTypeSyntheticEnvironmentDescriptor() {
        return new SimulationXmlType.SyntheticEnvironmentDescriptor();
    }

}
