//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:18 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.runtime;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import edu.pitt.gallowdd.persephone.xml.common.CountryCodeXmlEnum;
import edu.pitt.gallowdd.persephone.xml.common.PopVersionXmlEnum;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for simulationXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simulationXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="home_directory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="population_directory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="start_date" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="end_date" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="rng_seed" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="synthetic_environment_descriptor" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="country" type="{http://persephone.gallowdd.pitt.edu/xml/common}countryCodeXmlEnum"/&gt;
 *                   &lt;element name="version" type="{http://persephone.gallowdd.pitt.edu/xml/common}popVersionXmlEnum"/&gt;
 *                   &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simulationXmlType", propOrder = {
    "homeDirectory",
    "populationDirectory",
    "startDate",
    "endDate",
    "rngSeed",
    "syntheticEnvironmentDescriptor"
})
public class SimulationXmlType {

    @XmlElement(name = "home_directory", required = true)
    protected String homeDirectory;
    @XmlElement(name = "population_directory", required = true)
    protected String populationDirectory;
    @XmlElement(name = "start_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "end_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "rng_seed", required = true)
    protected BigInteger rngSeed;
    @XmlElement(name = "synthetic_environment_descriptor", required = true)
    protected List<SimulationXmlType.SyntheticEnvironmentDescriptor> syntheticEnvironmentDescriptor;

    /**
     * Gets the value of the homeDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomeDirectory() {
        return homeDirectory;
    }

    /**
     * Sets the value of the homeDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomeDirectory(String value) {
        this.homeDirectory = value;
    }

    /**
     * Gets the value of the populationDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPopulationDirectory() {
        return populationDirectory;
    }

    /**
     * Sets the value of the populationDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPopulationDirectory(String value) {
        this.populationDirectory = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the rngSeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRngSeed() {
        return rngSeed;
    }

    /**
     * Sets the value of the rngSeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRngSeed(BigInteger value) {
        this.rngSeed = value;
    }

    /**
     * Gets the value of the syntheticEnvironmentDescriptor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the syntheticEnvironmentDescriptor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSyntheticEnvironmentDescriptor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimulationXmlType.SyntheticEnvironmentDescriptor }
     * 
     * 
     */
    public List<SimulationXmlType.SyntheticEnvironmentDescriptor> getSyntheticEnvironmentDescriptor() {
        if (syntheticEnvironmentDescriptor == null) {
            syntheticEnvironmentDescriptor = new ArrayList<SimulationXmlType.SyntheticEnvironmentDescriptor>();
        }
        return this.syntheticEnvironmentDescriptor;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="country" type="{http://persephone.gallowdd.pitt.edu/xml/common}countryCodeXmlEnum"/&gt;
     *         &lt;element name="version" type="{http://persephone.gallowdd.pitt.edu/xml/common}popVersionXmlEnum"/&gt;
     *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "country",
        "version",
        "identifier"
    })
    public static class SyntheticEnvironmentDescriptor {

        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected CountryCodeXmlEnum country;
        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected PopVersionXmlEnum version;
        @XmlElement(required = true)
        protected String identifier;

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link CountryCodeXmlEnum }
         *     
         */
        public CountryCodeXmlEnum getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link CountryCodeXmlEnum }
         *     
         */
        public void setCountry(CountryCodeXmlEnum value) {
            this.country = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link PopVersionXmlEnum }
         *     
         */
        public PopVersionXmlEnum getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link PopVersionXmlEnum }
         *     
         */
        public void setVersion(PopVersionXmlEnum value) {
            this.version = value;
        }

        /**
         * Gets the value of the identifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentifier() {
            return identifier;
        }

        /**
         * Sets the value of the identifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentifier(String value) {
            this.identifier = value;
        }

    }

}
