//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:27 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.common;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for binaryNumericalOperationXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="binaryNumericalOperationXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="left_operand" type="{http://persephone.gallowdd.pitt.edu/xml/common}operandXmlType"/&gt;
 *         &lt;element name="operator" type="{http://persephone.gallowdd.pitt.edu/xml/common}mathematicalBinaryOperatorTypeXmlEnum"/&gt;
 *         &lt;element name="right_operand" type="{http://persephone.gallowdd.pitt.edu/xml/common}operandXmlType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "binaryNumericalOperationXmlType", propOrder = {
    "leftOperand",
    "operator",
    "rightOperand"
})
public class BinaryNumericalOperationXmlType {

    @XmlElement(name = "left_operand", required = true)
    protected OperandXmlType leftOperand;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected MathematicalBinaryOperatorTypeXmlEnum operator;
    @XmlElement(name = "right_operand", required = true)
    protected OperandXmlType rightOperand;

    /**
     * Gets the value of the leftOperand property.
     * 
     * @return
     *     possible object is
     *     {@link OperandXmlType }
     *     
     */
    public OperandXmlType getLeftOperand() {
        return leftOperand;
    }

    /**
     * Sets the value of the leftOperand property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperandXmlType }
     *     
     */
    public void setLeftOperand(OperandXmlType value) {
        this.leftOperand = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link MathematicalBinaryOperatorTypeXmlEnum }
     *     
     */
    public MathematicalBinaryOperatorTypeXmlEnum getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MathematicalBinaryOperatorTypeXmlEnum }
     *     
     */
    public void setOperator(MathematicalBinaryOperatorTypeXmlEnum value) {
        this.operator = value;
    }

    /**
     * Gets the value of the rightOperand property.
     * 
     * @return
     *     possible object is
     *     {@link OperandXmlType }
     *     
     */
    public OperandXmlType getRightOperand() {
        return rightOperand;
    }

    /**
     * Sets the value of the rightOperand property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperandXmlType }
     *     
     */
    public void setRightOperand(OperandXmlType value) {
        this.rightOperand = value;
    }

}
