//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:27 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.common;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for conditionXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="conditionXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="transmission_mode"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="none"/&gt;
 *               &lt;enumeration value="vector"/&gt;
 *               &lt;enumeration value="proximity"/&gt;
 *               &lt;enumeration value="network"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="exposed_state" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="state" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="wait_rule"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="special"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;enumeration value="zero"/&gt;
 *                                   &lt;enumeration value="infinite"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="hours" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                             &lt;element name="days" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                             &lt;element name="dynamic_agent_variable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="global_variable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="until_hour_of_day" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="until_sim_datetime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="default_next_state" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="transition_rule" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="next_state" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="resolver"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;choice&gt;
 *                                       &lt;element name="probability" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                                       &lt;element name="if" type="{http://persephone.gallowdd.pitt.edu/xml/common}ifStatementXmlType"/&gt;
 *                                     &lt;/choice&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "conditionXmlType", propOrder = {
    "transmissionMode",
    "exposedState",
    "state"
})
public class ConditionXmlType {

    @XmlElement(name = "transmission_mode", required = true)
    protected String transmissionMode;
    @XmlElement(name = "exposed_state", required = true)
    protected String exposedState;
    @XmlElement(required = true)
    protected List<ConditionXmlType.State> state;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the transmissionMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransmissionMode() {
        return transmissionMode;
    }

    /**
     * Sets the value of the transmissionMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransmissionMode(String value) {
        this.transmissionMode = value;
    }

    /**
     * Gets the value of the exposedState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExposedState() {
        return exposedState;
    }

    /**
     * Sets the value of the exposedState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExposedState(String value) {
        this.exposedState = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the state property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConditionXmlType.State }
     * 
     * 
     */
    public List<ConditionXmlType.State> getState() {
        if (state == null) {
            state = new ArrayList<ConditionXmlType.State>();
        }
        return this.state;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="wait_rule"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="special"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;enumeration value="zero"/&gt;
     *                         &lt;enumeration value="infinite"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="hours" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *                   &lt;element name="days" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *                   &lt;element name="dynamic_agent_variable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="global_variable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="until_hour_of_day" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="until_sim_datetime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="default_next_state" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="transition_rule" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="next_state" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="resolver"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;choice&gt;
     *                             &lt;element name="probability" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *                             &lt;element name="if" type="{http://persephone.gallowdd.pitt.edu/xml/common}ifStatementXmlType"/&gt;
     *                           &lt;/choice&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "waitRule",
        "defaultNextState",
        "transitionRule"
    })
    public static class State {

        @XmlElement(name = "wait_rule", required = true)
        protected ConditionXmlType.State.WaitRule waitRule;
        @XmlElement(name = "default_next_state", required = true)
        protected String defaultNextState;
        @XmlElement(name = "transition_rule")
        protected List<ConditionXmlType.State.TransitionRule> transitionRule;
        @XmlAttribute(name = "name", required = true)
        protected String name;

        /**
         * Gets the value of the waitRule property.
         * 
         * @return
         *     possible object is
         *     {@link ConditionXmlType.State.WaitRule }
         *     
         */
        public ConditionXmlType.State.WaitRule getWaitRule() {
            return waitRule;
        }

        /**
         * Sets the value of the waitRule property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConditionXmlType.State.WaitRule }
         *     
         */
        public void setWaitRule(ConditionXmlType.State.WaitRule value) {
            this.waitRule = value;
        }

        /**
         * Gets the value of the defaultNextState property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefaultNextState() {
            return defaultNextState;
        }

        /**
         * Sets the value of the defaultNextState property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefaultNextState(String value) {
            this.defaultNextState = value;
        }

        /**
         * Gets the value of the transitionRule property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the transitionRule property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTransitionRule().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ConditionXmlType.State.TransitionRule }
         * 
         * 
         */
        public List<ConditionXmlType.State.TransitionRule> getTransitionRule() {
            if (transitionRule == null) {
                transitionRule = new ArrayList<ConditionXmlType.State.TransitionRule>();
            }
            return this.transitionRule;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="next_state" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="resolver"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;choice&gt;
         *                   &lt;element name="probability" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
         *                   &lt;element name="if" type="{http://persephone.gallowdd.pitt.edu/xml/common}ifStatementXmlType"/&gt;
         *                 &lt;/choice&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nextState",
            "resolver"
        })
        public static class TransitionRule {

            @XmlElement(name = "next_state", required = true)
            protected String nextState;
            @XmlElement(required = true)
            protected ConditionXmlType.State.TransitionRule.Resolver resolver;

            /**
             * Gets the value of the nextState property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNextState() {
                return nextState;
            }

            /**
             * Sets the value of the nextState property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNextState(String value) {
                this.nextState = value;
            }

            /**
             * Gets the value of the resolver property.
             * 
             * @return
             *     possible object is
             *     {@link ConditionXmlType.State.TransitionRule.Resolver }
             *     
             */
            public ConditionXmlType.State.TransitionRule.Resolver getResolver() {
                return resolver;
            }

            /**
             * Sets the value of the resolver property.
             * 
             * @param value
             *     allowed object is
             *     {@link ConditionXmlType.State.TransitionRule.Resolver }
             *     
             */
            public void setResolver(ConditionXmlType.State.TransitionRule.Resolver value) {
                this.resolver = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;choice&gt;
             *         &lt;element name="probability" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
             *         &lt;element name="if" type="{http://persephone.gallowdd.pitt.edu/xml/common}ifStatementXmlType"/&gt;
             *       &lt;/choice&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "probability",
                "_if"
            })
            public static class Resolver {

                protected Float probability;
                @XmlElement(name = "if")
                protected IfStatementXmlType _if;

                /**
                 * Gets the value of the probability property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Float }
                 *     
                 */
                public Float getProbability() {
                    return probability;
                }

                /**
                 * Sets the value of the probability property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Float }
                 *     
                 */
                public void setProbability(Float value) {
                    this.probability = value;
                }

                /**
                 * Gets the value of the if property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link IfStatementXmlType }
                 *     
                 */
                public IfStatementXmlType getIf() {
                    return _if;
                }

                /**
                 * Sets the value of the if property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link IfStatementXmlType }
                 *     
                 */
                public void setIf(IfStatementXmlType value) {
                    this._if = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="special"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;enumeration value="zero"/&gt;
         *               &lt;enumeration value="infinite"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="hours" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
         *         &lt;element name="days" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
         *         &lt;element name="dynamic_agent_variable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="global_variable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="until_hour_of_day" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="until_sim_datetime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "special",
            "hours",
            "days",
            "dynamicAgentVariable",
            "globalVariable",
            "untilHourOfDay",
            "untilSimDatetime"
        })
        public static class WaitRule {

            protected String special;
            protected BigInteger hours;
            protected BigInteger days;
            @XmlElement(name = "dynamic_agent_variable")
            protected String dynamicAgentVariable;
            @XmlElement(name = "global_variable")
            protected String globalVariable;
            @XmlElement(name = "until_hour_of_day")
            protected String untilHourOfDay;
            @XmlElement(name = "until_sim_datetime")
            protected String untilSimDatetime;

            /**
             * Gets the value of the special property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSpecial() {
                return special;
            }

            /**
             * Sets the value of the special property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSpecial(String value) {
                this.special = value;
            }

            /**
             * Gets the value of the hours property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getHours() {
                return hours;
            }

            /**
             * Sets the value of the hours property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setHours(BigInteger value) {
                this.hours = value;
            }

            /**
             * Gets the value of the days property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getDays() {
                return days;
            }

            /**
             * Sets the value of the days property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setDays(BigInteger value) {
                this.days = value;
            }

            /**
             * Gets the value of the dynamicAgentVariable property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDynamicAgentVariable() {
                return dynamicAgentVariable;
            }

            /**
             * Sets the value of the dynamicAgentVariable property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDynamicAgentVariable(String value) {
                this.dynamicAgentVariable = value;
            }

            /**
             * Gets the value of the globalVariable property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGlobalVariable() {
                return globalVariable;
            }

            /**
             * Sets the value of the globalVariable property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGlobalVariable(String value) {
                this.globalVariable = value;
            }

            /**
             * Gets the value of the untilHourOfDay property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUntilHourOfDay() {
                return untilHourOfDay;
            }

            /**
             * Sets the value of the untilHourOfDay property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUntilHourOfDay(String value) {
                this.untilHourOfDay = value;
            }

            /**
             * Gets the value of the untilSimDatetime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUntilSimDatetime() {
                return untilSimDatetime;
            }

            /**
             * Sets the value of the untilSimDatetime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUntilSimDatetime(String value) {
                this.untilSimDatetime = value;
            }

        }

    }

}
