//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:27 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.common;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for datatypeXmlEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="datatypeXmlEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="String"/&gt;
 *     &lt;enumeration value="int"/&gt;
 *     &lt;enumeration value="double"/&gt;
 *     &lt;enumeration value="boolean"/&gt;
 *     &lt;enumeration value="void"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "datatypeXmlEnum")
@XmlEnum
public enum DatatypeXmlEnum {

    @XmlEnumValue("String")
    STRING("String"),
    @XmlEnumValue("int")
    INT("int"),
    @XmlEnumValue("double")
    DOUBLE("double"),
    @XmlEnumValue("boolean")
    BOOLEAN("boolean"),
    @XmlEnumValue("void")
    VOID("void");
    private final String value;

    DatatypeXmlEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DatatypeXmlEnum fromValue(String v) {
        for (DatatypeXmlEnum c: DatatypeXmlEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
