//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:27 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.common;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dynamicFunctionXmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dynamicFunctionXmlType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="java_classname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="return_data_type" type="{http://persephone.gallowdd.pitt.edu/xml/common}datatypeXmlEnum"/&gt;
 *         &lt;element name="parameters" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="param_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="param_data_type" type="{http://persephone.gallowdd.pitt.edu/xml/common}datatypeXmlEnum"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dynamicFunctionXmlType", propOrder = {
    "javaClassname",
    "returnDataType",
    "parameters"
})
public class DynamicFunctionXmlType {

    @XmlElement(name = "java_classname")
    protected String javaClassname;
    @XmlElement(name = "return_data_type", required = true)
    @XmlSchemaType(name = "string")
    protected DatatypeXmlEnum returnDataType;
    protected List<DynamicFunctionXmlType.Parameters> parameters;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the javaClassname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavaClassname() {
        return javaClassname;
    }

    /**
     * Sets the value of the javaClassname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavaClassname(String value) {
        this.javaClassname = value;
    }

    /**
     * Gets the value of the returnDataType property.
     * 
     * @return
     *     possible object is
     *     {@link DatatypeXmlEnum }
     *     
     */
    public DatatypeXmlEnum getReturnDataType() {
        return returnDataType;
    }

    /**
     * Sets the value of the returnDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatatypeXmlEnum }
     *     
     */
    public void setReturnDataType(DatatypeXmlEnum value) {
        this.returnDataType = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the parameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DynamicFunctionXmlType.Parameters }
     * 
     * 
     */
    public List<DynamicFunctionXmlType.Parameters> getParameters() {
        if (parameters == null) {
            parameters = new ArrayList<DynamicFunctionXmlType.Parameters>();
        }
        return this.parameters;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="param_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="param_data_type" type="{http://persephone.gallowdd.pitt.edu/xml/common}datatypeXmlEnum"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "paramName",
        "paramDataType"
    })
    public static class Parameters {

        @XmlElement(name = "param_name", required = true)
        protected String paramName;
        @XmlElement(name = "param_data_type", required = true)
        @XmlSchemaType(name = "string")
        protected DatatypeXmlEnum paramDataType;

        /**
         * Gets the value of the paramName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParamName() {
            return paramName;
        }

        /**
         * Sets the value of the paramName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParamName(String value) {
            this.paramName = value;
        }

        /**
         * Gets the value of the paramDataType property.
         * 
         * @return
         *     possible object is
         *     {@link DatatypeXmlEnum }
         *     
         */
        public DatatypeXmlEnum getParamDataType() {
            return paramDataType;
        }

        /**
         * Sets the value of the paramDataType property.
         * 
         * @param value
         *     allowed object is
         *     {@link DatatypeXmlEnum }
         *     
         */
        public void setParamDataType(DatatypeXmlEnum value) {
            this.paramDataType = value;
        }

    }

}
