//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 11:32:27 AM EDT 
//


package edu.pitt.gallowdd.persephone.xml.common;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for locationFilenameXmlEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="locationFilenameXmlEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="households.csv"/&gt;
 *     &lt;enumeration value="workplaces.csv"/&gt;
 *     &lt;enumeration value="schools.csv"/&gt;
 *     &lt;enumeration value="college_dorms.csv"/&gt;
 *     &lt;enumeration value="prisons.csv"/&gt;
 *     &lt;enumeration value="nursing_facilities.csv"/&gt;
 *     &lt;enumeration value="military_barracks.csv"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "locationFilenameXmlEnum")
@XmlEnum
public enum LocationFilenameXmlEnum {

    @XmlEnumValue("households.csv")
    HOUSEHOLDS_CSV("households.csv"),
    @XmlEnumValue("workplaces.csv")
    WORKPLACES_CSV("workplaces.csv"),
    @XmlEnumValue("schools.csv")
    SCHOOLS_CSV("schools.csv"),
    @XmlEnumValue("college_dorms.csv")
    COLLEGE_DORMS_CSV("college_dorms.csv"),
    @XmlEnumValue("prisons.csv")
    PRISONS_CSV("prisons.csv"),
    @XmlEnumValue("nursing_facilities.csv")
    NURSING_FACILITIES_CSV("nursing_facilities.csv"),
    @XmlEnumValue("military_barracks.csv")
    MILITARY_BARRACKS_CSV("military_barracks.csv");
    private final String value;

    LocationFilenameXmlEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LocationFilenameXmlEnum fromValue(String v) {
        for (LocationFilenameXmlEnum c: LocationFilenameXmlEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
